<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jennifer Tim-Diamond for Rainfall Health">
<meta name="dcterms.date" content="2026-09-01">
<meta name="description" content="New Jersey’s 44 TEAM-mandated hospitals post the worst readmissions profile of any large state roster in CMS’s Transforming Episode Accountability Model — verified against live CMS data, not the ‘nation’s highest’ headline number that circulates.">

<title>CMS TEAM in New Jersey: 44 Hospitals and the Nation’s Worst Readmissions Profile Among Large TEAM States – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


<link rel="stylesheet" href="../../styles/report.css">
<link rel="stylesheet" href="../../styles/stratus-media.css">
<link rel="stylesheet" href="styles/report.css">
<meta property="og:title" content="CMS TEAM in New Jersey: 44 Hospitals and the Nation’s Worst Readmissions Profile Among Large TEAM States">
<meta property="og:description" content="New Jersey’s 44 TEAM-mandated hospitals post the worst readmissions profile of any large state roster in CMS’s Transforming Episode Accountability Model — verified against live CMS data.">
<meta property="og:image" content="assets/rainfall-logo.png">
<meta property="og:site_name" content="Stratus">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="CMS TEAM in New Jersey: 44 Hospitals and the Nation’s Worst Readmissions Profile Among Large TEAM States">
<meta name="twitter:description" content="New Jersey’s 44 TEAM-mandated hospitals post the worst readmissions profile of any large state roster in CMS’s Transforming Episode Accountability Model — verified against live CMS data.">
<meta name="twitter:image" content="assets/rainfall-logo.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">01 · At a glance</a></li>
  <li><a href="#where-the-mandate-sits" id="toc-where-the-mandate-sits" class="nav-link" data-scroll-target="#where-the-mandate-sits">02 · Where the mandate sits</a></li>
  <li><a href="#guide-narrative-from-the-website-team-report" id="toc-guide-narrative-from-the-website-team-report" class="nav-link" data-scroll-target="#guide-narrative-from-the-website-team-report">03 · Guide narrative (from the website TEAM report)</a>
  <ul class="collapse">
  <li><a href="#new-jerseys-team-mandate-one-cbsa-all-44-hospitals" id="toc-new-jerseys-team-mandate-one-cbsa-all-44-hospitals" class="nav-link" data-scroll-target="#new-jerseys-team-mandate-one-cbsa-all-44-hospitals">New Jersey’s TEAM mandate: one CBSA, all 44 hospitals</a></li>
  <li><a href="#the-nj-paradox-high-resources-high-penalties" id="toc-the-nj-paradox-high-resources-high-penalties" class="nav-link" data-scroll-target="#the-nj-paradox-high-resources-high-penalties">The NJ paradox: high resources, high penalties</a></li>
  <li><a href="#complete-hospital-directory" id="toc-complete-hospital-directory" class="nav-link" data-scroll-target="#complete-hospital-directory">Complete hospital directory</a></li>
  <li><a href="#health-system-concentration-and-team-leverage" id="toc-health-system-concentration-and-team-leverage" class="nav-link" data-scroll-target="#health-system-concentration-and-team-leverage">Health system concentration and TEAM leverage</a></li>
  <li><a href="#what-this-analysis-does-not-estimate" id="toc-what-this-analysis-does-not-estimate" class="nav-link" data-scroll-target="#what-this-analysis-does-not-estimate">What this analysis does not estimate</a></li>
  <li><a href="#frequently-asked-questions" id="toc-frequently-asked-questions" class="nav-link" data-scroll-target="#frequently-asked-questions">Frequently asked questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CMS TEAM in New Jersey: 44 Hospitals and the Nation’s Worst Readmissions Profile Among Large TEAM States</h1>
</div>

<div>
  <div class="description">
    New Jersey’s 44 TEAM-mandated hospitals post the worst readmissions profile of any large state roster in CMS’s Transforming Episode Accountability Model — verified against live CMS data, not the ‘nation’s highest’ headline number that circulates.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jennifer Tim-Diamond for Rainfall Health </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="wp-cover">
<p><img src="assets/rainfall-logo.png" class="wp-logo img-fluid"></p>
<p class="wp-kicker">
White paper
</p>
<section id="cms-team-in-new-jersey-44-hospitals-and-the-nations-worst-readmissions-profile-among-large-team-states" class="level1">
<h1>CMS TEAM in New Jersey: 44 Hospitals and the Nation’s Worst Readmissions Profile Among Large TEAM States</h1>
<p class="wp-dek">
44 mandated hospitals · 1 CBSA · before PY2 (2027)
</p>
<p class="wp-meta">
Jennifer Tim-Diamond for Rainfall Health · September 2026<br>Every CMS TEAM-mandated hospital in New Jersey, verified against the live CMS roster and readmissions data — including where the widely repeated “nation’s highest” HRRP claim overstates, and understates, the real story.
</p>
</section>
</div>
<div class="wp-listen-card">
<audio id="wp-audio" src="audio/index-narration.mp3" preload="metadata">
</audio>
<div class="wp-listen-panel">
<div class="wp-listen-grid">
<div class="wp-listen-main">
<p class="wp-listen-kicker">
Rainfall white paper · Narration
</p>
<p class="wp-listen-title">
Listen while you read
</p>
<div class="wp-listen-toolbar">
<button type="button" class="wp-play" data-action="play-pause" aria-label="Play" aria-pressed="false">
<span class="wp-play-glyph" aria-hidden="true"></span>
</button>
<button type="button" class="wp-icon-btn" data-action="back-15" aria-label="Back 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M9 7v4H4l5 5V7z"></path><path d="M13 7a5 5 0 1 1 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<button type="button" class="wp-icon-btn wp-speed-btn" data-action="speed-dial" aria-label="Playback speed 1×">
<span data-role="speed-label">1×</span>
</button>
<button type="button" class="wp-icon-btn" data-action="forward-15" aria-label="Forward 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M15 7v4h5l-5 5V7z"></path><path d="M11 7a5 5 0 1 0 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<p><span class="wp-time" aria-live="polite"><span data-role="time-current">00:00</span> / <span data-role="time-duration">00:00</span></span></p>
</div>
<p><input type="range" class="wp-seek" data-action="seek" min="0" max="100" value="0" step="0.1" aria-label="Seek"></p>
</div>
</div>
</div>
</div>
<div class="wp-action-bar">
<p><a class="wp-action" href="index.pdf">Download PDF</a> <a class="wp-action" href="index-narration.txt" download="index-narration.txt">Narration script</a></p>
</div>
<div class="wp-disclaimer">
<p><strong>Methodology.</strong> Hospital counts, CBSA breakdowns, figures 1–2, and the readmissions comparison recompute on render from vendored CMS data (the TEAM participant list and HRRP dataset 9n3s-kdb3, joined by CCN). Episode-dollar and Medicare-population figures are not invented here; where this repo has no verified source, the report says so rather than repeating an unsourced estimate.</p>
</div>
<section id="at-a-glance" class="level1">
<h1>01 · At a glance</h1>
<p>Live hospital counts come from the vendored CMS TEAM participant list. The HRRP row below is computed at render time from the CMS HRRP dataset (9n3s-kdb3) joined to this scope’s roster by CCN; Medicare-population and per-episode LEJR figures are not published at hospital level, so this report states that rather than estimating them.</p>
<div class="cell">
<div id="tbl-glance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Signal</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mandated hospitals</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">NY–NJ metro overlap</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBSAs</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">Largest CBSA: New York–Newark–Jersey City, NY–NJ ( 44 hospitals)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medicare beneficiaries</td>
<td style="text-align: left;">Not computed in this pipeline</td>
<td style="text-align: left;">Covered-lives scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">HRRP (all conditions)</td>
<td style="text-align: left;">61.9% vs 48.1% national</td>
<td style="text-align: left;">Readmission pressure under episode accountability</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Est. annual LEJR</td>
<td style="text-align: left;">Not published at hospital level</td>
<td style="text-align: left;">Volume concentration</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="where-the-mandate-sits" class="level1">
<h1>02 · Where the mandate sits</h1>
<p>Largest market in this scope: <strong>New York–Newark–Jersey City, NY–NJ</strong> (44 hospitals).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1-cbsa.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CMS TEAM-mandated hospitals in this scope.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New York–Newark–Jersey City, NY–NJ</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig2-region.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Concentration of TEAM-mandated hospitals.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="guide-narrative-from-the-website-team-report" class="level1">
<h1>03 · Guide narrative (from the website TEAM report)</h1>
<section id="takeaways" class="level3">
<h3 class="anchored" data-anchor-id="takeaways">Takeaways</h3>
<ul>
<li>44 hospitals — all in the NY–NJ metro CBSA</li>
<li>New Jersey’s HRRP excess-readmission rate is 61.9% vs 48.1% nationally — the worst of any large-roster TEAM state, though not literally the single highest nationally once every TEAM state is checked</li>
<li>Unlike New York, New Jersey runs <em>above</em> the national rate on hip/knee replacement, TEAM’s core procedure category — the one condition where a favorable split would matter most, and New Jersey doesn’t have it</li>
<li>Hackensack Meridian Health and RWJBarnabas Health are the two largest systems in scope</li>
<li>Shared CBSA with 65 New York hospitals, all competing for the same post-acute capacity</li>
</ul>
</section>
<section id="new-jerseys-team-mandate-one-cbsa-all-44-hospitals" class="level2">
<h2 class="anchored" data-anchor-id="new-jerseys-team-mandate-one-cbsa-all-44-hospitals">New Jersey’s TEAM mandate: one CBSA, all 44 hospitals</h2>
<p>All 44 CMS TEAM-mandated hospitals in New Jersey fall within a single Core-Based Statistical Area: the <strong>New York–Newark–Jersey City, NY–NJ metropolitan CBSA</strong>. This is not a planning anomaly but a reflection of economic geography: northern and central New Jersey form a single integrated labor market, commuter economy, and care delivery system with New York City. Patients from Bergen County may receive surgical care at Hackensack University Medical Center, recover at a New Jersey SNF, and receive outpatient follow-up from a Manhattan specialist — all within one TEAM episode window.</p>
<p>The implications for TEAM management are significant. New Jersey hospitals compete for post-acute placements — skilled nursing facilities, inpatient rehabilitation facilities, home health agencies — with 65 simultaneously mandated New York hospitals in the same metro area. The shared CBSA does not mean shared target prices: CMS sets hospital-specific targets based on each institution’s own historical spending blend with regional benchmarks. But it does mean that the post-acute market these hospitals depend on is simultaneously under pressure from 109 hospitals all trying to reduce episode costs at once.</p>
<p>CMS does not publish hospital-level TEAM episode volumes, so this report does not model a New Jersey-specific episode count the way an earlier version of this briefing did — doing so would mean presenting an invented number as New Jersey data.</p>
<p><strong>Fast facts</strong></p>
<ul>
<li>44 hospitals mandated — all in the New York–Newark–Jersey City, NY–NJ CBSA</li>
<li>61.9% of NJ hospital-condition pairs exceed HRRP ERR 1.0, vs 48.1% nationally — worst among large-roster TEAM states</li>
<li>CMS does not publish hospital-level LEJR episode volumes; this report does not estimate one for New Jersey</li>
<li>Major systems in scope: Hackensack Meridian Health, RWJBarnabas Health, Atlantic Health System</li>
</ul>
</section>
<section id="the-nj-paradox-high-resources-high-penalties" class="level2">
<h2 class="anchored" data-anchor-id="the-nj-paradox-high-resources-high-penalties">The NJ paradox: high resources, high penalties</h2>
<p>Joining New Jersey’s live TEAM roster to the CMS HRRP dataset (9n3s-kdb3, performance period 07/01/2021–06/30/2024) by CCN, all 44 of New Jersey’s 44 mandated hospitals appear in the HRRP file. Across those hospitals’ condition pairs, <strong>61.9%</strong> exceed the excess readmission ratio (ERR) threshold of 1.0, against <strong>48.1%</strong> nationally. That gap is real — this is the worst readmissions profile of any state with a large TEAM roster (20-plus mandated hospitals) that this repo has checked.</p>
<p>It is worth being precise about the “nation’s highest” framing that circulates for New Jersey, because checking it against every TEAM-participating state changes the story slightly. A handful of states with very small TEAM rosters — Indiana (6 hospitals), Georgia (13), Missouri (6) — post higher pooled rates than New Jersey, but a rate computed from a handful of hospitals is far noisier than one computed from 44. Among states with a roster large enough for the number to mean something, New Jersey’s 61.9% is the worst this analysis found.</p>
<p>Unlike New York, whose readmissions story splits favorably on hip and knee replacement specifically, New Jersey’s version of that split runs the other way. New Jersey’s hip and knee replacement ERR runs <em>above</em> the national rate: 56% of NJ hip and knee pairs exceed the threshold, against 47.9% nationally — the opposite of what New York shows. Pneumonia is the widest gap of all, at 75% against 46.8% nationally. The one exception is CABG, where New Jersey actually runs <em>below</em> the national rate (40% vs 49.9%) — but CABG is a small slice of New Jersey’s TEAM volume, and it doesn’t offset the pattern on hip and knee, the procedure category TEAM weights most heavily.</p>
<p>New Jersey is not under-resourced. <strong>Hackensack Meridian Health</strong> and <strong>RWJBarnabas Health</strong> are both large integrated systems with extensive post-acute partnerships, not under-staffed community hospitals with no quality infrastructure. Several hypotheses could explain the gap despite that scale. First, <strong>density creates competition for post-acute placements</strong>: in a market with 109 TEAM-mandated hospitals (44 in New Jersey, 65 in New York) all trying to place patients in lower-cost post-acute settings at once, skilled nursing and home health capacity constraints can push marginal placements toward higher-cost options or premature discharge home. Second, <strong>patient complexity in urban NJ markets</strong> is high, though HRRP’s risk adjustment is designed to account for this. Neither hypothesis is verified against hospital-level data in this report; they are offered as plausible explanations, not findings.</p>
<p>For TEAM purposes, the practical risk is straightforward: a hospital that already runs hot on HRRP readmissions across every tracked condition, including the ones TEAM prices directly, is structurally exposed to the same clinical failure pattern showing up as above-target episode costs once two-sided risk begins.</p>
<p>(Source: <a href="https://data.cms.gov/provider-data/dataset/9n3s-kdb3">Centers for Medicare &amp; Medicaid Services. HRRP supplemental data, Dataset 9n3s-kdb3.</a> — vendored copy joined to the CMS TEAM participant list by CCN for this report.)</p>
</section>
<section id="complete-hospital-directory" class="level2">
<h2 class="anchored" data-anchor-id="complete-hospital-directory">Complete hospital directory</h2>
<p>All 44 New Jersey hospitals mandated for CMS TEAM are listed below, generated at render time from the same live roster used for the counts above.</p>
<div class="cell">
<div id="tbl-directory-nj" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-directory-nj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-directory-nj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Hospital</th>
<th style="text-align: left;">CCN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bayonne University Hospital</td>
<td style="text-align: left;">310025</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bayshore Medical Center</td>
<td style="text-align: left;">310112</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bergen New Bridge Medical Center</td>
<td style="text-align: left;">310058</td>
</tr>
<tr class="even">
<td style="text-align: left;">Carewell Health Medical Center</td>
<td style="text-align: left;">310083</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Centrastate Medical Center</td>
<td style="text-align: left;">310111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chilton Medical Center</td>
<td style="text-align: left;">310017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clara Maass Medical Center</td>
<td style="text-align: left;">310009</td>
</tr>
<tr class="even">
<td style="text-align: left;">Community Medical Center</td>
<td style="text-align: left;">310041</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cooperman Barnabas Medical Center</td>
<td style="text-align: left;">310076</td>
</tr>
<tr class="even">
<td style="text-align: left;">Englewood Hospital</td>
<td style="text-align: left;">310045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hackensack Meridian Health Pascack Valley Medical</td>
<td style="text-align: left;">310130</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hackensack Meridian Mountainside Medical</td>
<td style="text-align: left;">310054</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hackensack University Medical Center</td>
<td style="text-align: left;">310001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heights University Hospital</td>
<td style="text-align: left;">310016</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hoboken University Hospital</td>
<td style="text-align: left;">310040</td>
</tr>
<tr class="even">
<td style="text-align: left;">Holy Name Medical Center</td>
<td style="text-align: left;">310008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hunterdon Medical Center</td>
<td style="text-align: left;">310005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jersey City Medical Center</td>
<td style="text-align: left;">310074</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jersey Shore University Medical Center</td>
<td style="text-align: left;">310073</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jfk University Medical Center</td>
<td style="text-align: left;">310108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monmouth Medical Center</td>
<td style="text-align: left;">310075</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monmouth Medical Center-Southern Campus</td>
<td style="text-align: left;">310084</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Morristown Medical Center</td>
<td style="text-align: left;">310015</td>
</tr>
<tr class="even">
<td style="text-align: left;">Newark Beth Israel Medical Center</td>
<td style="text-align: left;">310002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Newton Medical Center</td>
<td style="text-align: left;">310028</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ocean University Medical Center</td>
<td style="text-align: left;">310052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overlook Medical Center</td>
<td style="text-align: left;">310051</td>
</tr>
<tr class="even">
<td style="text-align: left;">Palisades Medical Center</td>
<td style="text-align: left;">310003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Penn Medicine Princeton Medical Center</td>
<td style="text-align: left;">310010</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raritan Bay Medical Center</td>
<td style="text-align: left;">310039</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Riverview Medical Center</td>
<td style="text-align: left;">310034</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robert Wood Johnson University Hospital</td>
<td style="text-align: left;">310038</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Robert Wood Johnson University Hospital Somerset</td>
<td style="text-align: left;">310048</td>
</tr>
<tr class="even">
<td style="text-align: left;">Robert Wood Johnson University Hospital at Rahway</td>
<td style="text-align: left;">310024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saint Clare’s Hospital</td>
<td style="text-align: left;">310050</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saint Michael’s Medical Center</td>
<td style="text-align: left;">310096</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saint Peter’s University Hospital</td>
<td style="text-align: left;">310070</td>
</tr>
<tr class="even">
<td style="text-align: left;">Secaucus University Hospital</td>
<td style="text-align: left;">310118</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Southern Ocean Medical Center</td>
<td style="text-align: left;">310113</td>
</tr>
<tr class="even">
<td style="text-align: left;">St Joseph’s University Medical Center Inc</td>
<td style="text-align: left;">310019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">St Mary’s General Hospital</td>
<td style="text-align: left;">310006</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trinitas Regional Medical Center</td>
<td style="text-align: left;">310027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">University Hospital</td>
<td style="text-align: left;">310119</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valley Hospital</td>
<td style="text-align: left;">310012</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>(Source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">Centers for Medicare &amp; Medicaid Services (2026). TEAM participant list.</a>)</p>
</section>
<section id="health-system-concentration-and-team-leverage" class="level2">
<h2 class="anchored" data-anchor-id="health-system-concentration-and-team-leverage">Health system concentration and TEAM leverage</h2>
<p><strong>Hackensack Meridian Health</strong> and <strong>RWJBarnabas Health</strong> are the two largest systems represented on the New Jersey TEAM roster, each with roughly nine or more mandated facilities, including Hackensack Meridian’s flagship Hackensack University Medical Center and RWJBarnabas’s flagship Cooperman Barnabas Medical Center. This repo doesn’t carry a verified, CCN-level system-affiliation map for New Jersey the way California’s report does for its systems, so exact per-system counts here are approximate, not audited — a hospital’s own system membership should be confirmed directly rather than taken from this table. Directionally, that concentration still matters for TEAM management: vertically integrated post-acute networks and shared quality protocols can be deployed consistently across a large system’s episode volume in a way a standalone community hospital cannot match.</p>
<p><strong>University Hospital</strong>, the only publicly-owned academic medical center in New Jersey (the clinical partner of Rutgers New Jersey Medical School), and <strong>Bergen New Bridge Medical Center</strong> (county-owned) are the safety-net facilities in the NJ TEAM cohort. Institutions like these typically serve a higher share of Medicaid and uninsured patients, which is worth flagging as a Track 2 eligibility question for those specific hospitals, though this report doesn’t have verified payer-mix data to confirm eligibility.</p>
</section>
<section id="what-this-analysis-does-not-estimate" class="level2">
<h2 class="anchored" data-anchor-id="what-this-analysis-does-not-estimate">What this analysis does not estimate</h2>
<p>CMS does not publish hospital-level TEAM episode volumes or target prices in a form this repo can join to the New Jersey roster, so this report does not model a New Jersey-specific episode count, target price, or gain/loss dollar figure. Optum Advisory (2025) projected that 56% of TEAM-mandated hospitals nationally will lose money once downside risk begins in Performance Year 2, averaging $1.2 million per facility — a national estimate, not a New Jersey-specific one, and its underlying methodology isn’t public. Given New Jersey’s readmissions profile, that national risk is plausibly more acute here than the average state, but this report does not attach a number to that intuition. A hospital that wants an actual dollar estimate needs its own CMS-issued target price file, obtained through the TEAM participant portal.</p>
<p>The most effective intervention, supported by both the Dummit et al.&nbsp;(2016) and Finkelstein et al.&nbsp;(2021) research bases, is reducing discharge to institutional post-acute care (IRFs and SNFs) in favor of home health for clinically appropriate patients. In New Jersey, where IRF and SNF placement rates have historically been high given proximity to facilities and physician incentive structures, this represents both the largest opportunity and the most organizationally challenging change.</p>
<p>(Source: <a href="https://doi.org/10.1001/jama.2021.5684">Finkelstein et al.&nbsp;(2021), JAMA 325(18).</a>)</p>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently asked questions</h2>
<section id="how-many-new-jersey-hospitals-are-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-many-new-jersey-hospitals-are-in-cms-team">How many New Jersey hospitals are in CMS TEAM?</h3>
<p>44 New Jersey hospitals are mandated to participate in CMS TEAM, all within the New York–Newark–Jersey City, NY–NJ CBSA, per the March 2026 CMS participant list.</p>
</section>
<section id="does-new-jersey-have-the-worst-readmission-performance-under-hrrp" class="level3">
<h3 class="anchored" data-anchor-id="does-new-jersey-have-the-worst-readmission-performance-under-hrrp">Does New Jersey have the worst readmission performance under HRRP?</h3>
<p>Among states with a large TEAM roster, yes. 61.9% of New Jersey’s hospital-condition pairs exceed the ERR 1.0 threshold in the CMS HRRP dataset, versus 48.1% nationally — the worst of any state with 20 or more TEAM-mandated hospitals that this analysis checked, ahead of Florida and Massachusetts. A few states with very small TEAM rosters (Indiana, Georgia, Missouri) post higher rates still, but those are computed from a handful of hospitals each, which is a much noisier number than New Jersey’s 44.</p>
</section>
<section id="are-all-new-jersey-hospitals-in-the-same-cbsa" class="level3">
<h3 class="anchored" data-anchor-id="are-all-new-jersey-hospitals-in-the-same-cbsa">Are all New Jersey hospitals in the same CBSA?</h3>
<p>Yes. All 44 NJ TEAM hospitals are in the New York–Newark–Jersey City, NY–NJ CBSA — a multi-state market shared with 65 New York hospitals.</p>
</section>
<section id="is-hackensack-university-medical-center-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="is-hackensack-university-medical-center-in-cms-team">Is Hackensack University Medical Center in CMS TEAM?</h3>
<p>Yes. Hackensack University Medical Center is on the CMS TEAM participant list. Multiple other Hackensack Meridian Health facilities are also mandated.</p>
</section>
<section id="when-does-nj-hospitals-team-downside-risk-begin" class="level3">
<h3 class="anchored" data-anchor-id="when-does-nj-hospitals-team-downside-risk-begin">When does NJ hospitals’ TEAM downside risk begin?</h3>
<p>Performance Year 1 (2026) has no downside risk. Most NJ hospitals move to Track 3 (20%/20%) in PY2 (2027), though safety-net and county hospitals may qualify for Track 2.</p>
</section>
<section id="why-does-new-jersey-have-such-a-high-readmission-penalty-rate-if-it-has-well-resourced-systems" class="level3">
<h3 class="anchored" data-anchor-id="why-does-new-jersey-have-such-a-high-readmission-penalty-rate-if-it-has-well-resourced-systems">Why does New Jersey have such a high readmission penalty rate if it has well-resourced systems?</h3>
<p>Research suggests several factors: competitive post-acute markets where capacity constraints drive suboptimal placement; patient complexity in dense urban NJ counties; and historically high IRF/SNF utilization that has not been systematically reduced despite large system scale.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Centers for Medicare &amp; Medicaid Services. (2026). TEAM participant list (March 2026 update). CMMI. https://www.cms.gov/priorities/innovation/innovation-models/team-model</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024, August). Transforming Episode Accountability Model: Final Rule. Federal Register, 89(166), 68986–69178. https://www.federalregister.gov/documents/2024/08/28/2024-17021/medicare-program-hospital-inpatient-prospective-payment-systems</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024). Hospital Readmissions Reduction Program (HRRP) FY2025 supplemental data [Data set]. CMS Provider Data Catalog, Dataset 9n3s-kdb3. https://data.cms.gov/provider-data/dataset/9n3s-kdb3</li>
<li>Dummit, L. A., Kahvecioglu, D., Marrufo, G., Rajkumar, R., Marshall, J., Tan, E., Le, S. T., Terebelo, S., Hearld, L., Xian, Y., Morishima, C., Pittman, P., Barzee, B., &amp; Conway, P. H. (2016). Association between hospital participation in a Medicare bundled payment initiative and payments and quality outcomes for lower extremity joint replacement episodes. JAMA, 316(12), 1267–1278. https://doi.org/10.1001/jama.2016.12717</li>
<li>Finkelstein, A., Ji, Y., Mahoney, N., &amp; Skinner, J. (2021). Mandatory Medicare bundled payment program for lower extremity joint replacement and discharge to institutional postacute care. JAMA, 325(18), 1879–1890. https://doi.org/10.1001/jama.2021.5684</li>
<li>Zuckerman, R. B., Sheingold, S. H., Orav, E. J., Ruhter, J., &amp; Epstein, A. M. (2016). Readmissions, observation, and the Hospital Readmissions Reduction Program. New England Journal of Medicine, 374(16), 1543–1551. https://doi.org/10.1056/NEJMsa1513024</li>
<li>Navathe, A. S., Liao, J. M., Emanuel, E. J., &amp; Press, M. J. (2020). Opening a two-way street for bundled payments. JAMA, 323(2), 121–122. https://doi.org/10.1001/jama.2019.19040</li>
<li>Optum Advisory. (2025, November). What hospitals need to know about TEAM for 2026. Advisory.com. https://www.advisory.com/topics/policy-and-payment/hospitals-need-to-know-team</li>
</ol>
<div class="wp-disclaimer">
<p><strong>Disclaimer.</strong> Rainfall Health is not a hospital, health system, or health care provider. This paper is prepared by health care industry professionals, not clinicians, and does not constitute clinical, legal, financial, or regulatory advice. Roster counts and readmission figures are computed from the CMS files cited above; this paper does not assess, rate, or make claims about the quality of care provided by any individual hospital or organization.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="scripts/listen-along.js" defer=""></script>
<script src="scripts/highlight-notes.js" defer=""></script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>