<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jennifer Tim-Diamond for Rainfall Health">
<meta name="dcterms.date" content="2026-09-01">
<meta name="description" content="Massachusetts’s 37 TEAM-mandated hospitals post a 57.9% HRRP excess-readmission rate versus 48.1% nationally — verified against live CMS data, not the ‘62.5%, second nationally’ headline number that circulates.">

<title>CMS TEAM in Massachusetts: 37 Mandated Hospitals, Strong on Hip and Knee, Hot on Everything Else – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


<link rel="stylesheet" href="../../styles/report.css">
<link rel="stylesheet" href="../../styles/stratus-media.css">
<link rel="stylesheet" href="styles/report.css">
<meta property="og:title" content="CMS TEAM in Massachusetts: 37 Mandated Hospitals, Strong on Hip and Knee, Hot on Everything Else">
<meta property="og:description" content="Massachusetts’s 37 TEAM-mandated hospitals post a 57.9% HRRP excess-readmission rate versus 48.1% nationally — verified against live CMS data.">
<meta property="og:image" content="assets/rainfall-logo.png">
<meta property="og:site_name" content="Stratus">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="CMS TEAM in Massachusetts: 37 Mandated Hospitals, Strong on Hip and Knee, Hot on Everything Else">
<meta name="twitter:description" content="Massachusetts’s 37 TEAM-mandated hospitals post a 57.9% HRRP excess-readmission rate versus 48.1% nationally — verified against live CMS data.">
<meta name="twitter:image" content="assets/rainfall-logo.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">01 · At a glance</a></li>
  <li><a href="#where-the-mandate-sits" id="toc-where-the-mandate-sits" class="nav-link" data-scroll-target="#where-the-mandate-sits">02 · Where the mandate sits</a></li>
  <li><a href="#guide-narrative-from-the-website-team-report" id="toc-guide-narrative-from-the-website-team-report" class="nav-link" data-scroll-target="#guide-narrative-from-the-website-team-report">03 · Guide narrative (from the website TEAM report)</a>
  <ul class="collapse">
  <li><a href="#the-massachusetts-team-market-academic-concentration-one-dominant-cbsa" id="toc-the-massachusetts-team-market-academic-concentration-one-dominant-cbsa" class="nav-link" data-scroll-target="#the-massachusetts-team-market-academic-concentration-one-dominant-cbsa">The Massachusetts TEAM market: academic concentration, one dominant CBSA</a></li>
  <li><a href="#the-academic-medicine-readmission-picture-worse-on-medical-conditions-not-on-hip-and-knee" id="toc-the-academic-medicine-readmission-picture-worse-on-medical-conditions-not-on-hip-and-knee" class="nav-link" data-scroll-target="#the-academic-medicine-readmission-picture-worse-on-medical-conditions-not-on-hip-and-knee">The academic medicine readmission picture: worse on medical conditions, not on hip and knee</a></li>
  <li><a href="#complete-hospital-directory" id="toc-complete-hospital-directory" class="nav-link" data-scroll-target="#complete-hospital-directory">Complete hospital directory</a></li>
  <li><a href="#health-system-concentration-and-team-leverage" id="toc-health-system-concentration-and-team-leverage" class="nav-link" data-scroll-target="#health-system-concentration-and-team-leverage">Health system concentration and TEAM leverage</a></li>
  <li><a href="#what-this-analysis-does-not-estimate" id="toc-what-this-analysis-does-not-estimate" class="nav-link" data-scroll-target="#what-this-analysis-does-not-estimate">What this analysis does not estimate</a></li>
  <li><a href="#frequently-asked-questions" id="toc-frequently-asked-questions" class="nav-link" data-scroll-target="#frequently-asked-questions">Frequently asked questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CMS TEAM in Massachusetts: 37 Mandated Hospitals, Strong on Hip and Knee, Hot on Everything Else</h1>
</div>

<div>
  <div class="description">
    Massachusetts’s 37 TEAM-mandated hospitals post a 57.9% HRRP excess-readmission rate versus 48.1% nationally — verified against live CMS data, not the ‘62.5%, second nationally’ headline number that circulates.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jennifer Tim-Diamond for Rainfall Health </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="wp-cover">
<p><img src="assets/rainfall-logo.png" class="wp-logo img-fluid"></p>
<p class="wp-kicker">
White paper
</p>
<section id="cms-team-in-massachusetts-37-mandated-hospitals-strong-on-hip-and-knee-hot-on-everything-else" class="level1">
<h1>CMS TEAM in Massachusetts: 37 Mandated Hospitals, Strong on Hip and Knee, Hot on Everything Else</h1>
<p class="wp-dek">
37 mandated hospitals · 4 CBSAs · before PY2 (2027)
</p>
<p class="wp-meta">
Jennifer Tim-Diamond for Rainfall Health · September 2026<br>Every CMS TEAM-mandated hospital in Massachusetts, verified against the live CMS roster and readmissions data — including where the widely repeated “62.5%, second nationally” HRRP claim overstates the number and gets the ranking wrong.
</p>
</section>
</div>
<div class="wp-listen-card">
<audio id="wp-audio" src="audio/index-narration.mp3" preload="metadata">
</audio>
<div class="wp-listen-panel">
<div class="wp-listen-grid">
<div class="wp-listen-main">
<p class="wp-listen-kicker">
Rainfall white paper · Narration
</p>
<p class="wp-listen-title">
Listen while you read
</p>
<div class="wp-listen-toolbar">
<button type="button" class="wp-play" data-action="play-pause" aria-label="Play" aria-pressed="false">
<span class="wp-play-glyph" aria-hidden="true"></span>
</button>
<button type="button" class="wp-icon-btn" data-action="back-15" aria-label="Back 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M9 7v4H4l5 5V7z"></path><path d="M13 7a5 5 0 1 1 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<button type="button" class="wp-icon-btn wp-speed-btn" data-action="speed-dial" aria-label="Playback speed 1×">
<span data-role="speed-label">1×</span>
</button>
<button type="button" class="wp-icon-btn" data-action="forward-15" aria-label="Forward 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M15 7v4h5l-5 5V7z"></path><path d="M11 7a5 5 0 1 0 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<p><span class="wp-time" aria-live="polite"><span data-role="time-current">00:00</span> / <span data-role="time-duration">00:00</span></span></p>
</div>
<p><input type="range" class="wp-seek" data-action="seek" min="0" max="100" value="0" step="0.1" aria-label="Seek"></p>
</div>
</div>
</div>
</div>
<div class="wp-action-bar">
<p><a class="wp-action" href="index.pdf">Download PDF</a> <a class="wp-action" href="index-narration.txt" download="index-narration.txt">Narration script</a></p>
</div>
<div class="wp-disclaimer">
<p><strong>Methodology.</strong> Hospital counts, CBSA breakdowns, figures 1–2, and the readmissions comparison recompute on render from vendored CMS data (the TEAM participant list and HRRP dataset 9n3s-kdb3, joined by CCN). Episode-dollar and Medicare-population figures are not invented here; where this repo has no verified source, the report says so rather than repeating an unsourced estimate.</p>
</div>
<section id="at-a-glance" class="level1">
<h1>01 · At a glance</h1>
<p>Live hospital counts come from the vendored CMS TEAM participant list. The HRRP row below is computed at render time from the CMS HRRP dataset (9n3s-kdb3) joined to this scope’s roster by CCN; Medicare-population and per-episode LEJR figures are not published at hospital level, so this report states that rather than estimating them.</p>
<div class="cell">
<div id="tbl-glance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 27%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Signal</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mandated hospitals</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">Academic Boston concentration</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBSAs</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Largest CBSA: Boston–Cambridge–Newton, MA–NH ( 30 hospitals)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medicare beneficiaries</td>
<td style="text-align: left;">Not computed in this pipeline</td>
<td style="text-align: left;">Covered-lives scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">HRRP (all conditions)</td>
<td style="text-align: left;">57.9% vs 48.1% national</td>
<td style="text-align: left;">Readmission pressure under episode accountability</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Est. annual LEJR</td>
<td style="text-align: left;">Not published at hospital level</td>
<td style="text-align: left;">Volume concentration</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="where-the-mandate-sits" class="level1">
<h1>02 · Where the mandate sits</h1>
<p>Largest market in this scope: <strong>Boston–Cambridge–Newton, MA–NH</strong> (30 hospitals).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1-cbsa.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CMS TEAM-mandated hospitals in this scope.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Boston–Cambridge–Newton, MA–NH</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">81.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Providence–Warwick, RI–MA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Barnstable Town</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Worcester</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig2-region.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Concentration of TEAM-mandated hospitals.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="guide-narrative-from-the-website-team-report" class="level1">
<h1>03 · Guide narrative (from the website TEAM report)</h1>
<section id="takeaways" class="level3">
<h3 class="anchored" data-anchor-id="takeaways">Takeaways</h3>
<ul>
<li>37 hospitals across 4 CBSAs — all mandatory, none voluntary</li>
<li>Boston–Cambridge–Newton, MA–NH holds 30 of 37 (81%)</li>
<li>Massachusetts’s HRRP excess-readmission rate is 57.9% vs 48.1% nationally — worse than the national rate, though not literally the “second-highest nationally” figure that circulates</li>
<li>Unlike New Jersey, Massachusetts runs <em>below</em> the national rate on hip and knee replacement, TEAM’s core procedure category — the state’s readmissions problem sits almost entirely in the medical conditions HRRP also tracks</li>
<li>Mass General Brigham and Beth Israel Lahey Health are the two largest systems in scope</li>
</ul>
</section>
<section id="the-massachusetts-team-market-academic-concentration-one-dominant-cbsa" class="level2">
<h2 class="anchored" data-anchor-id="the-massachusetts-team-market-academic-concentration-one-dominant-cbsa">The Massachusetts TEAM market: academic concentration, one dominant CBSA</h2>
<p>Massachusetts has <strong>37 hospitals</strong> mandated to participate in CMS TEAM across <strong>four CBSAs</strong>, with 30 of those — <strong>81%</strong> — located in the Boston–Cambridge–Newton, MA–NH metropolitan CBSA. The remaining seven split across Providence–Warwick, RI–MA (4), Barnstable Town/Cape Cod (2), and Worcester (1). The concentration of academic medical centers in the Boston market is without parallel in American healthcare: <strong>Massachusetts General Hospital</strong>, <strong>Brigham and Women’s Hospital</strong>, <strong>Beth Israel Deaconess Medical Center</strong>, <strong>Tufts Medical Center</strong>, and <strong>Boston Medical Center</strong> are all subject to the same TEAM accountability structures as every community hospital in the state.</p>
<p>All 37 Massachusetts hospitals are mandatory participants — there is no voluntary cohort in this state’s TEAM roster.</p>
<p>CMS does not publish hospital-level TEAM episode volumes, so this report does not model a Massachusetts-specific episode count the way an earlier version of this briefing did — doing so would mean presenting an invented number as Massachusetts data.</p>
<p><strong>Fast facts</strong></p>
<ul>
<li>37 hospitals mandated across 4 CBSAs — all mandatory</li>
<li>Boston–Cambridge–Newton, MA–NH: 30 hospitals (81% of state total)</li>
<li>Providence–Warwick, RI–MA: 4 hospitals</li>
<li>Barnstable Town (Cape Cod): 2 hospitals</li>
<li>Worcester: 1 hospital (UMass Memorial Medical Center)</li>
<li>57.9% of MA hospital-condition pairs exceed HRRP ERR 1.0, vs 48.1% nationally</li>
<li>CMS does not publish hospital-level LEJR episode volumes; this report does not estimate one for Massachusetts</li>
<li>Major systems in scope: Mass General Brigham, Beth Israel Lahey Health, Boston Medical Center Health System, Tufts Medicine, Southcoast Health</li>
</ul>
</section>
<section id="the-academic-medicine-readmission-picture-worse-on-medical-conditions-not-on-hip-and-knee" class="level2">
<h2 class="anchored" data-anchor-id="the-academic-medicine-readmission-picture-worse-on-medical-conditions-not-on-hip-and-knee">The academic medicine readmission picture: worse on medical conditions, not on hip and knee</h2>
<p>Joining Massachusetts’s live TEAM roster to the CMS HRRP dataset (9n3s-kdb3, performance period 07/01/2021–06/30/2024) by CCN, 36 of Massachusetts’s 37 mandated hospitals appear in the HRRP file. Across those hospitals’ condition pairs, <strong>57.9%</strong> exceed the excess readmission ratio (ERR) threshold of 1.0, against <strong>48.1%</strong> nationally. That is a real gap — but it is not the <strong>62.5%, second-highest nationally, behind only New Jersey</strong> figure that circulates for Massachusetts. The real pooled rate is 57.9%, and checking every TEAM-participating state shows Massachusetts is not in second place.</p>
<p>A handful of states with very small TEAM rosters — Indiana (74.1%, 6 hospitals), Georgia (64.9%, 13 hospitals), and Missouri (63.0%, 6 hospitals) — post higher pooled rates than Massachusetts, but a rate computed from a handful of hospitals is far noisier than one computed from 37. Among states with large TEAM rosters, New Jersey (61.9%, 44 hospitals) and Florida (61.4%, 40 hospitals) both post higher pooled rates than Massachusetts as well. Massachusetts’s 57.9% places it well behind that group — roughly sixth among large-roster TEAM states by this analysis, not second.</p>
<p>The more useful finding sits in how the number breaks down by condition. On <strong>hip and knee replacement</strong> — the procedure category TEAM prices most heavily — Massachusetts runs <em>favorably</em>: only 32.4% of MA hip and knee pairs exceed the threshold, against 47.9% nationally. That’s a meaningfully better-than-national split, similar in shape to what New York’s roster shows. CABG sits close to parity: 54.5% of MA pairs above the threshold against 49.9% nationally.</p>
<p>The gap opens up on the medical conditions HRRP also tracks, outside TEAM’s surgical categories. Heart attack runs notably worse: % of MA pairs above the threshold against % nationally. Heart failure runs 60% against 48.9% nationally. Pneumonia runs 65.7% against 46.8% nationally. COPD runs 65.7% against 47.2% nationally. Those four medical conditions, not the surgical categories TEAM prices, are what drive Massachusetts’s overall HRRP number above the national line.</p>
<p>Massachusetts is not under-resourced. <strong>Mass General Brigham</strong> and <strong>Beth Israel Lahey Health</strong> are both large integrated systems with extensive post-acute partnerships and some of the most sophisticated care-management infrastructure in the country. Several hypotheses could explain the medical-condition gap despite that scale. First, <strong>complexity concentration</strong>: Massachusetts academic centers treat disproportionately complex, often out-of-state-referred patients whose post-discharge needs may exceed what HRRP’s risk adjustment fully captures. Second, <strong>market density</strong>: the Boston metro area has a high concentration of SNFs, IRFs, and home health agencies, but also high demand for those same placements from many competing acute-care systems at once. Neither hypothesis is verified against hospital-level data in this report; they are offered as plausible explanations, not findings.</p>
<p>For TEAM purposes, the practical read is specific rather than sweeping: Massachusetts hospitals should not assume their overall HRRP reputation predicts their TEAM performance. On the procedure category TEAM actually prices most heavily, hip and knee replacement, the state’s mandated hospitals are running ahead of the national rate, not behind it. The exposure sits in the medical conditions, which matter for HRRP but are not what TEAM’s episode payments are built around.</p>
<p>(Source: <a href="https://data.cms.gov/provider-data/dataset/9n3s-kdb3">Centers for Medicare &amp; Medicaid Services. HRRP supplemental data, Dataset 9n3s-kdb3.</a> — vendored copy joined to the CMS TEAM participant list by CCN for this report.)</p>
</section>
<section id="complete-hospital-directory" class="level2">
<h2 class="anchored" data-anchor-id="complete-hospital-directory">Complete hospital directory</h2>
<p>All 37 Massachusetts hospitals mandated for CMS TEAM are listed below, generated at render time from the same live roster used for the counts above.</p>
<div class="cell">
<div id="tbl-directory-ma" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-directory-ma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-directory-ma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Hospital</th>
<th style="text-align: left;">CCN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anna Jaques Hospital</td>
<td style="text-align: left;">220029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beth Israel Deaconess Hospital - Needham</td>
<td style="text-align: left;">220083</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Beth Israel Deaconess Hospital - Plymouth</td>
<td style="text-align: left;">220060</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beth Israel Deaconess Hospital-Milton Inc</td>
<td style="text-align: left;">220108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Beth Israel Deaconess Medical Center</td>
<td style="text-align: left;">220086</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beverly Hospital Corporation</td>
<td style="text-align: left;">220033</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boston Medical Center Corporation-</td>
<td style="text-align: left;">220031</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boston Medical Center-Brighton</td>
<td style="text-align: left;">220036</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boston Medical Center-South</td>
<td style="text-align: left;">220111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brigham and Women’s Faulkner Hospital</td>
<td style="text-align: left;">220119</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brigham and Women’s Hospital</td>
<td style="text-align: left;">220110</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brown University Health Morton Hospital</td>
<td style="text-align: left;">220073</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brown University Health Saint Anne’s Hospital</td>
<td style="text-align: left;">220020</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cambridge Health Alliance</td>
<td style="text-align: left;">220011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cape Cod Hospital</td>
<td style="text-align: left;">220012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emerson Hospital -</td>
<td style="text-align: left;">220084</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Falmouth Hospital</td>
<td style="text-align: left;">220135</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lahey Hospital &amp; Medical Center, Burlington</td>
<td style="text-align: left;">220171</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lowell General Hospital</td>
<td style="text-align: left;">220063</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marlborough Hospital</td>
<td style="text-align: left;">220049</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts Eye and Ear Infirmary -</td>
<td style="text-align: left;">220075</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts General Hospital</td>
<td style="text-align: left;">220071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Melrosewakefield Healthcare</td>
<td style="text-align: left;">220070</td>
</tr>
<tr class="even">
<td style="text-align: left;">Merrimack Health Lawrence Hospital</td>
<td style="text-align: left;">220010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Merrimack Health Methuen Hospital</td>
<td style="text-align: left;">220080</td>
</tr>
<tr class="even">
<td style="text-align: left;">Metrowest Medical Center</td>
<td style="text-align: left;">220175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mount Auburn Hospital</td>
<td style="text-align: left;">220002</td>
</tr>
<tr class="even">
<td style="text-align: left;">New England Baptist Hospital</td>
<td style="text-align: left;">220088</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Newton-Wellesley Hospital</td>
<td style="text-align: left;">220101</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Shore Medical Center -</td>
<td style="text-align: left;">220035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Signature Healthcare Brockton Hospital</td>
<td style="text-align: left;">220052</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Shore Hospital</td>
<td style="text-align: left;">220100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Southcoast Hospital Group, Inc</td>
<td style="text-align: left;">220074</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sturdy Memorial Hospital</td>
<td style="text-align: left;">220008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tufts Medical Center</td>
<td style="text-align: left;">220116</td>
</tr>
<tr class="even">
<td style="text-align: left;">Umass Memorial Medical Center Inc</td>
<td style="text-align: left;">220163</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Winchester Hospital</td>
<td style="text-align: left;">220105</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>(Source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">Centers for Medicare &amp; Medicaid Services (2026). TEAM participant list.</a>)</p>
</section>
<section id="health-system-concentration-and-team-leverage" class="level2">
<h2 class="anchored" data-anchor-id="health-system-concentration-and-team-leverage">Health system concentration and TEAM leverage</h2>
<p><strong>Mass General Brigham</strong> — formed by the merger of Massachusetts General Hospital and Brigham and Women’s Hospital and their affiliated networks — is the largest health system in New England and one of the most complex TEAM participants in the country. Its mandated hospitals span flagship academic centers (Massachusetts General, Brigham and Women’s, Brigham and Women’s Faulkner) to community hospitals (Newton–Wellesley, North Shore Medical Center). <strong>Beth Israel Lahey Health</strong>, formed by the 2019 merger of Beth Israel Deaconess Medical Center and Lahey Health, brings together BIDMC and its Plymouth, Needham, and Milton satellites with Lahey Hospital &amp; Medical Center Burlington under one TEAM-accountable system still in the process of integrating clinical protocols and post-acute networks across previously independent hospitals.</p>
<p>This repo doesn’t carry a verified, CCN-level system-affiliation map for Massachusetts the way California’s report does for its systems, so system groupings described here are directional, not audited — a hospital’s own system membership should be confirmed directly rather than taken from this report. Directionally, that concentration still matters for TEAM management: vertically integrated post-acute networks and shared quality protocols can be deployed consistently across a large system’s episode volume in a way a standalone community hospital cannot match.</p>
<p><strong>New England Baptist Hospital</strong>, a specialty orthopedic hospital in Boston recently brought into Mass General Brigham amid Steward Health’s bankruptcy proceedings, is a particular case study in TEAM exposure: it is one of New England’s highest-volume joint replacement programs, and its TEAM target prices — set against its historically efficient orthopedic episode profile — will test whether that efficiency advantage holds once TEAM’s external accountability benchmarks apply.</p>
</section>
<section id="what-this-analysis-does-not-estimate" class="level2">
<h2 class="anchored" data-anchor-id="what-this-analysis-does-not-estimate">What this analysis does not estimate</h2>
<p>CMS does not publish hospital-level TEAM episode volumes or target prices in a form this repo can join to the Massachusetts roster, so this report does not model a Massachusetts-specific episode count, target price, or gain/loss dollar figure. Optum Advisory (2025) projected that 56% of TEAM-mandated hospitals nationally will lose money once downside risk begins in Performance Year 2, averaging $1.2 million per facility — a national estimate, not a Massachusetts-specific one, and its underlying methodology isn’t public. Given that Massachusetts’s readmissions exposure is concentrated in medical conditions TEAM doesn’t price rather than in the surgical categories it does, this report does not attach a Massachusetts-specific dollar figure to that national estimate. A hospital that wants an actual dollar estimate needs its own CMS-issued target price file, obtained through the TEAM participant portal.</p>
<p>The most effective intervention, supported by both the Dummit et al.&nbsp;(2016) and Finkelstein et al.&nbsp;(2021) research bases, is reducing discharge to institutional post-acute care (IRFs and SNFs) in favor of home health for clinically appropriate patients. Massachusetts’s favorable hip and knee readmission split suggests its academic centers already manage that specific care pathway relatively well; the open question is whether the same coordination discipline can be extended to the medical conditions where the state’s hospitals currently run hot.</p>
<p>(Source: <a href="https://doi.org/10.1001/jama.2021.5684">Finkelstein et al.&nbsp;(2021), JAMA 325(18).</a>)</p>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently asked questions</h2>
<section id="how-many-massachusetts-hospitals-are-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-many-massachusetts-hospitals-are-in-cms-team">How many Massachusetts hospitals are in CMS TEAM?</h3>
<p>37 Massachusetts hospitals are mandated to participate in CMS TEAM, across four CBSAs, per the March 2026 CMS participant list. All 37 are mandatory participants.</p>
</section>
<section id="does-massachusetts-have-the-second-worst-readmission-performance-under-hrrp" class="level3">
<h3 class="anchored" data-anchor-id="does-massachusetts-have-the-second-worst-readmission-performance-under-hrrp">Does Massachusetts have the second-worst readmission performance under HRRP?</h3>
<p>No.&nbsp;That claim circulates but does not hold up against this repo’s live data. 57.9% of Massachusetts’s hospital-condition pairs exceed the ERR 1.0 threshold in the CMS HRRP dataset, versus 48.1% nationally — worse than the national rate, but not the second-highest among any comparison set this analysis checked. New Jersey (61.9%) and Florida (61.4%) both post higher pooled rates among large-roster TEAM states, and several small-roster states post higher rates still, though those are noisier numbers computed from a handful of hospitals each.</p>
</section>
<section id="are-massachusetts-hospitals-worse-than-average-on-hip-and-knee-replacement-the-procedure-team-prices-most-heavily" class="level3">
<h3 class="anchored" data-anchor-id="are-massachusetts-hospitals-worse-than-average-on-hip-and-knee-replacement-the-procedure-team-prices-most-heavily">Are Massachusetts hospitals worse than average on hip and knee replacement, the procedure TEAM prices most heavily?</h3>
<p>No — the opposite. Only 32.4% of Massachusetts hip and knee pairs exceed the HRRP threshold, against 47.9% nationally. Massachusetts’s overall HRRP number is pulled up by the medical conditions (heart attack, heart failure, pneumonia, COPD), not by the surgical categories TEAM’s episode payments are built around.</p>
</section>
<section id="are-all-massachusetts-hospitals-mandatory-participants" class="level3">
<h3 class="anchored" data-anchor-id="are-all-massachusetts-hospitals-mandatory-participants">Are all Massachusetts hospitals mandatory participants?</h3>
<p>Yes. All 37 Massachusetts TEAM hospitals are mandatory; none joined voluntarily.</p>
</section>
<section id="is-massachusetts-general-hospital-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="is-massachusetts-general-hospital-in-cms-team">Is Massachusetts General Hospital in CMS TEAM?</h3>
<p>Yes. Massachusetts General Hospital and Brigham and Women’s Hospital are both on the CMS TEAM participant list, in the Boston–Cambridge–Newton, MA–NH CBSA.</p>
</section>
<section id="when-does-massachusetts-hospitals-team-downside-risk-begin" class="level3">
<h3 class="anchored" data-anchor-id="when-does-massachusetts-hospitals-team-downside-risk-begin">When does Massachusetts hospitals’ TEAM downside risk begin?</h3>
<p>Performance Year 1 (2026) has no downside risk. Most Massachusetts hospitals move to two-sided risk in PY2 (2027), though safety-net hospitals may qualify for more forgiving stop-gain/stop-loss tracks.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Centers for Medicare &amp; Medicaid Services. (2026). TEAM participant list (March 2026 update). CMMI. https://www.cms.gov/priorities/innovation/innovation-models/team-model</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024, August). Transforming Episode Accountability Model: Final Rule. Federal Register, 89(166), 68986–69178. https://www.federalregister.gov/documents/2024/08/28/2024-17021/medicare-program-hospital-inpatient-prospective-payment-systems</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024). Hospital Readmissions Reduction Program (HRRP) FY2025 supplemental data [Data set]. CMS Provider Data Catalog, Dataset 9n3s-kdb3. https://data.cms.gov/provider-data/dataset/9n3s-kdb3</li>
<li>Dummit, L. A., Kahvecioglu, D., Marrufo, G., Rajkumar, R., Marshall, J., Tan, E., Le, S. T., Terebelo, S., Hearld, L., Xian, Y., Morishima, C., Pittman, P., Barzee, B., &amp; Conway, P. H. (2016). Association between hospital participation in a Medicare bundled payment initiative and payments and quality outcomes for lower extremity joint replacement episodes. JAMA, 316(12), 1267–1278. https://doi.org/10.1001/jama.2016.12717</li>
<li>Finkelstein, A., Ji, Y., Mahoney, N., &amp; Skinner, J. (2021). Mandatory Medicare bundled payment program for lower extremity joint replacement and discharge to institutional postacute care. JAMA, 325(18), 1879–1890. https://doi.org/10.1001/jama.2021.5684</li>
<li>Zuckerman, R. B., Sheingold, S. H., Orav, E. J., Ruhter, J., &amp; Epstein, A. M. (2016). Readmissions, observation, and the Hospital Readmissions Reduction Program. New England Journal of Medicine, 374(16), 1543–1551. https://doi.org/10.1056/NEJMsa1513024</li>
<li>Navathe, A. S., Liao, J. M., Emanuel, E. J., &amp; Press, M. J. (2020). Opening a two-way street for bundled payments. JAMA, 323(2), 121–122. https://doi.org/10.1001/jama.2019.19040</li>
<li>Healthcare Financial Management Association. (2026, March). Hospitals can use 2026 to prepare for CMS TEAM bundled payment risk. HFMA. https://www.hfma.org/payment-reimbursement-and-managed-care/hospitals-can-use-2026-to-prepare-for-cms-team-bundled-payment-risk</li>
</ol>
<div class="wp-disclaimer">
<p><strong>Disclaimer.</strong> Rainfall Health is not a hospital, health system, or health care provider. This paper is prepared by health care industry professionals, not clinicians, and does not constitute clinical, legal, financial, or regulatory advice. Roster counts and readmission figures are computed from the CMS files cited above; this paper does not assess, rate, or make claims about the quality of care provided by any individual hospital or organization.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="scripts/listen-along.js" defer=""></script>
<script src="scripts/highlight-notes.js" defer=""></script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>