<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jennifer Tim-Diamond for Rainfall Health">
<meta name="dcterms.date" content="2026-09-01">
<meta name="description" content="New York carries the second-largest state roster in CMS’s Transforming Episode Accountability Model. What the live CMS roster and readmissions data actually show — including where the state outperforms the national average.">

<title>CMS TEAM in New York: 78 Mandated Hospitals, the Nation’s Largest Bundled-Payment Market – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


<link rel="stylesheet" href="../../styles/report.css">
<link rel="stylesheet" href="../../styles/stratus-media.css">
<link rel="stylesheet" href="styles/report.css">
<meta property="og:title" content="CMS TEAM in New York: 78 Mandated Hospitals, the Nation’s Largest Bundled-Payment Market">
<meta property="og:description" content="New York carries the second-largest state roster in CMS’s Transforming Episode Accountability Model. What the live CMS roster and readmissions data actually show.">
<meta property="og:image" content="assets/rainfall-logo.png">
<meta property="og:site_name" content="Stratus">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="CMS TEAM in New York: 78 Mandated Hospitals, the Nation’s Largest Bundled-Payment Market">
<meta name="twitter:description" content="New York carries the second-largest state roster in CMS’s Transforming Episode Accountability Model. What the live CMS roster and readmissions data actually show.">
<meta name="twitter:image" content="assets/rainfall-logo.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">01 · At a glance</a></li>
  <li><a href="#where-the-mandate-sits" id="toc-where-the-mandate-sits" class="nav-link" data-scroll-target="#where-the-mandate-sits">02 · Where the mandate sits</a></li>
  <li><a href="#guide-narrative-from-the-website-team-report" id="toc-guide-narrative-from-the-website-team-report" class="nav-link" data-scroll-target="#guide-narrative-from-the-website-team-report">03 · Guide narrative (from the website TEAM report)</a>
  <ul class="collapse">
  <li><a href="#new-york-and-the-team-mandate-market-scope-and-stakes" id="toc-new-york-and-the-team-mandate-market-scope-and-stakes" class="nav-link" data-scroll-target="#new-york-and-the-team-mandate-market-scope-and-stakes">New York and the TEAM mandate: market scope and stakes</a></li>
  <li><a href="#market-context" id="toc-market-context" class="nav-link" data-scroll-target="#market-context">Market context</a></li>
  <li><a href="#complete-hospital-directory-by-cbsa" id="toc-complete-hospital-directory-by-cbsa" class="nav-link" data-scroll-target="#complete-hospital-directory-by-cbsa">Complete hospital directory by CBSA</a></li>
  <li><a href="#the-new-yorknewarkjersey-city-cbsa-a-shared-post-acute-market" id="toc-the-new-yorknewarkjersey-city-cbsa-a-shared-post-acute-market" class="nav-link" data-scroll-target="#the-new-yorknewarkjersey-city-cbsa-a-shared-post-acute-market">The New York–Newark–Jersey City CBSA: a shared post-acute market</a></li>
  <li><a href="#buffalo-and-upstate-cbsas" id="toc-buffalo-and-upstate-cbsas" class="nav-link" data-scroll-target="#buffalo-and-upstate-cbsas">Buffalo and upstate CBSAs</a></li>
  <li><a href="#readmissions-landscape-new-york-under-hrrp" id="toc-readmissions-landscape-new-york-under-hrrp" class="nav-link" data-scroll-target="#readmissions-landscape-new-york-under-hrrp">Readmissions landscape: New York under HRRP</a></li>
  <li><a href="#financial-exposure-what-this-report-does-and-doesnt-estimate" id="toc-financial-exposure-what-this-report-does-and-doesnt-estimate" class="nav-link" data-scroll-target="#financial-exposure-what-this-report-does-and-doesnt-estimate">Financial exposure: what this report does and doesn’t estimate</a></li>
  <li><a href="#what-new-york-hospitals-must-prioritize-in-2026" id="toc-what-new-york-hospitals-must-prioritize-in-2026" class="nav-link" data-scroll-target="#what-new-york-hospitals-must-prioritize-in-2026">What New York hospitals must prioritize in 2026</a></li>
  <li><a href="#frequently-asked-questions" id="toc-frequently-asked-questions" class="nav-link" data-scroll-target="#frequently-asked-questions">Frequently asked questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CMS TEAM in New York: 78 Mandated Hospitals, the Nation’s Largest Bundled-Payment Market</h1>
</div>

<div>
  <div class="description">
    New York carries the second-largest state roster in CMS’s Transforming Episode Accountability Model. What the live CMS roster and readmissions data actually show — including where the state outperforms the national average.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jennifer Tim-Diamond for Rainfall Health </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="wp-cover">
<p><img src="assets/rainfall-logo.png" class="wp-logo img-fluid"></p>
<p class="wp-kicker">
White paper
</p>
<section id="cms-team-in-new-york-78-mandated-hospitals-the-nations-largest-bundled-payment-market" class="level1">
<h1>CMS TEAM in New York: 78 Mandated Hospitals, the Nation’s Largest Bundled-Payment Market</h1>
<p class="wp-dek">
78 mandated hospitals · 6 CBSAs · Performance Year 2 begins January 2027
</p>
<p class="wp-meta">
Jennifer Tim-Diamond for Rainfall Health · September 2026<br>What New York’s live CMS TEAM roster and CMS readmissions data actually show — where the mandate sits, how participating hospitals perform today, and what changes in Performance Year 2.
</p>
</section>
</div>
<div class="wp-listen-card">
<audio id="wp-audio" src="audio/index-narration.mp3" preload="metadata">
</audio>
<div class="wp-listen-panel">
<div class="wp-listen-grid">
<div class="wp-listen-main">
<p class="wp-listen-kicker">
Rainfall white paper · Narration
</p>
<p class="wp-listen-title">
Listen while you read
</p>
<div class="wp-listen-toolbar">
<button type="button" class="wp-play" data-action="play-pause" aria-label="Play" aria-pressed="false">
<span class="wp-play-glyph" aria-hidden="true"></span>
</button>
<button type="button" class="wp-icon-btn" data-action="back-15" aria-label="Back 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M9 7v4H4l5 5V7z"></path><path d="M13 7a5 5 0 1 1 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<button type="button" class="wp-icon-btn wp-speed-btn" data-action="speed-dial" aria-label="Playback speed 1×">
<span data-role="speed-label">1×</span>
</button>
<button type="button" class="wp-icon-btn" data-action="forward-15" aria-label="Forward 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M15 7v4h5l-5 5V7z"></path><path d="M11 7a5 5 0 1 0 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<p><span class="wp-time" aria-live="polite"><span data-role="time-current">00:00</span> / <span data-role="time-duration">00:00</span></span></p>
</div>
<p><input type="range" class="wp-seek" data-action="seek" min="0" max="100" value="0" step="0.1" aria-label="Seek"></p>
</div>
</div>
</div>
</div>
<div class="wp-action-bar">
<p><a class="wp-action" href="index.pdf">Download PDF</a> <a class="wp-action" href="index-narration.txt" download="index-narration.txt">Narration script</a></p>
</div>
<div class="wp-disclaimer">
<p><strong>Methodology.</strong> Hospital counts, CBSA breakdowns, figures 1–2, and the readmissions comparison recompute on render from vendored CMS data (the TEAM participant list and HRRP dataset 9n3s-kdb3, joined by CCN). Episode-dollar and Medicare-population figures are not invented here; where this repo has no verified source, the report says so rather than repeating an unsourced estimate.</p>
</div>
<section id="at-a-glance" class="level1">
<h1>01 · At a glance</h1>
<p>Live hospital counts come from <code>data/territoryHospitals.json</code> (March 2026 CMS TEAM participant extract). The HRRP row below is computed at render time from the CMS HRRP dataset (9n3s-kdb3) joined to this scope’s roster by CCN; Medicare-population and per-episode LEJR figures are not published at hospital level, so this report states that rather than estimating them.</p>
<div class="cell">
<div id="tbl-glance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Signal</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mandated hospitals</td>
<td style="text-align: left;">78</td>
<td style="text-align: left;">Largest single-state TEAM market</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBSAs</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">Largest CBSA: New York–Newark–Jersey City, NY–NJ ( 65 hospitals)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medicare beneficiaries</td>
<td style="text-align: left;">Not computed in this pipeline</td>
<td style="text-align: left;">Covered-lives scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">HRRP (all conditions)</td>
<td style="text-align: left;">48.7% vs 48.1% national</td>
<td style="text-align: left;">Readmission pressure under episode accountability</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Est. annual LEJR</td>
<td style="text-align: left;">Not published at hospital level</td>
<td style="text-align: left;">Volume concentration</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="where-the-mandate-sits" class="level1">
<h1>02 · Where the mandate sits</h1>
<p>Largest market in this scope: <strong>New York–Newark–Jersey City, NY–NJ</strong> (65 hospitals).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1-cbsa.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CMS TEAM-mandated hospitals in this scope.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New York–Newark–Jersey City, NY–NJ</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">83.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Buffalo–Cheektowaga</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oneonta</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Batavia</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cortland</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massena–Ogdensburg</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig2-region.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Concentration of TEAM-mandated hospitals.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="guide-narrative-from-the-website-team-report" class="level1">
<h1>03 · Guide narrative (from the website TEAM report)</h1>
<section id="takeaways" class="level3">
<h3 class="anchored" data-anchor-id="takeaways">Takeaways</h3>
<ul>
<li>78 hospitals mandated — second nationally</li>
<li>65 in New York–Newark–Jersey City metro</li>
<li>New York’s HRRP excess-readmission rate is essentially at the national baseline, not meaningfully worse</li>
<li>NYU Langone, Mount Sinai, Montefiore in scope</li>
<li>Hip/knee replacement is TEAM’s core procedure category, and New York’s hip/knee readmission rate runs <em>below</em> the national rate</li>
</ul>
</section>
<section id="new-york-and-the-team-mandate-market-scope-and-stakes" class="level2">
<h2 class="anchored" data-anchor-id="new-york-and-the-team-mandate-market-scope-and-stakes">New York and the TEAM mandate: market scope and stakes</h2>
<p>New York State has <strong>78 hospitals</strong> mandated to participate in the CMS Transforming Episode Accountability Model across <strong>six Core-Based Statistical Areas</strong>, making it the second-largest TEAM state in the country behind California. TEAM covers five episode categories — lower extremity joint replacement (LEJR), surgical hip/femur fracture treatment, spinal fusion, major bowel procedures, and coronary artery bypass graft — but CMS does not publish hospital-level episode volumes, so this report does not model a New York-specific episode count.</p>
<p>The geographic concentration is striking. Sixty-five of the 78 mandated hospitals — <strong>83% of the state total</strong> — are located within the New York–Newark–Jersey City, NY–NJ metropolitan CBSA, the nation’s largest metropolitan bundled-payment market. This multi-state CBSA also contains all 44 mandated New Jersey hospitals, creating a shared post-acute ecosystem spanning two states, five boroughs, and suburban markets from Long Island to Westchester to northern New Jersey.</p>
<p>New York’s hospital market is among the most structurally complex in the country. Large nonprofit health systems (Northwell Health, Mount Sinai Health System, NYU Langone, NewYork-Presbyterian, Montefiore) coexist with city-operated public hospitals (NYC Health + Hospitals), academic medical centers, and smaller community facilities. This heterogeneity shapes TEAM performance unevenly: across the CMS HRRP dataset, New York’s TEAM-mandated hospitals as a group post a hip/knee excess-readmission rate <em>below</em> the national average, but individual large systems still show pockets of elevated risk — Mount Sinai West and Mount Sinai South Nassau both post hip/knee ERRs above 1.25, among the highest in the state’s roster.</p>
<p>(Source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">Centers for Medicare &amp; Medicaid Services (2026); Rainfall Health analysis.</a>)</p>
<p><strong>Fast facts</strong></p>
<ul>
<li>78 hospitals mandated (March 2026 CMS list)</li>
<li>6 CBSAs: New York–Newark–Jersey City (65), Buffalo–Cheektowaga (8), Oneonta (2), Batavia (1), Cortland (1), Massena–Ogdensburg (1)</li>
<li>CMS does not publish hospital-level LEJR episode volumes; this report does not estimate one for New York</li>
<li>48.7% of NY hospital-condition pairs in the CMS HRRP file exceed ERR 1.0 — essentially at the 48.1% national rate, not meaningfully worse</li>
<li>New York’s hip/knee-replacement ERR is <em>below</em> the national rate: 24.4% of NY hip/knee pairs exceed 1.0, versus 47.9% nationally</li>
<li>Top health systems by roster presence: Northwell Health, Mount Sinai, NYU Langone, Montefiore, NewYork-Presbyterian, NYC Health + Hospitals</li>
</ul>
</section>
<section id="market-context" class="level2">
<h2 class="anchored" data-anchor-id="market-context">Market context</h2>
<p>The state’s hospital market is dominated by large nonprofit systems that depend on Medicare as a primary revenue source, making TEAM’s financial implications consequential for the sector. This repo does not carry a verified per-state Medicare beneficiary count, so that figure is omitted rather than estimated.</p>
<p>Hospital costs in the New York metropolitan area are widely reported to run above national benchmarks, driven by labor costs, real estate expenses, and the density of academic and specialty care. CMS sets TEAM target prices using each hospital’s own historical spending blended with regional benchmarks, so a hospital’s own cost structure is partially reflected in its target; the 2.0% discount factor CMS applies to LEJR, SHFFT, and spinal fusion targets still creates a gap that must be closed through care coordination, not just baseline cost levels.</p>
<p>A landmark JAMA study by Dummit et al.&nbsp;(2016) analyzing the predecessor Comprehensive Joint Replacement (CJR) model — which also included New York markets — found that participating hospitals reduced episode payments by an average of $864 per episode in the first performance year. Finkelstein et al.&nbsp;(2021), analyzing mandatory bundled payments in lower extremity joint replacement, found that discharge to institutional post-acute care declined significantly under mandatory programs. Neither study isolates a New York-specific effect; they are cited here as the relevant evidence base for what mandatory bundling has done elsewhere, not as New York figures.</p>
<p>(Source: <a href="https://doi.org/10.1001/jama.2016.12717">Dummit et al.&nbsp;(2016), JAMA 316(12).</a>) (Source: <a href="https://doi.org/10.1001/jama.2021.5684">Finkelstein et al.&nbsp;(2021), JAMA 325(18).</a>)</p>
</section>
<section id="complete-hospital-directory-by-cbsa" class="level2">
<h2 class="anchored" data-anchor-id="complete-hospital-directory-by-cbsa">Complete hospital directory by CBSA</h2>
<p>The following table lists every CMS TEAM-mandated hospital in New York, organized by Core-Based Statistical Area, generated at render time from the same live roster used for the counts above — so it cannot drift out of sync with them or omit a participant.</p>
<div class="cell">
<div id="tbl-directory-by-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-directory-by-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-directory-by-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 97%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: left;">Hospitals in this CBSA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">New York–Newark–Jersey City, NY–NJ</td>
<td style="text-align: right;">65</td>
<td style="text-align: left;">Bellevue Hospital Center · Bronxcare Hospital Center · Brookdale Hospital Medical Center · Brooklyn Hospital Center - Downtown Campus · Elmhurst Hospital Center · Flushing Hospital Medical Center · Glen Cove Hospital · Good Samaritan Hospital Medical Center · Good Samaritan Hospital of Suffern · Harlem Hospital Center · Helen Hayes Hospital · Hospital for Special Surgery · Hudson Valley Hospital Center · Huntington Hospital · Jacobi Medical Center · Jamaica Hospital Medical Center · John t Mather Memorial Hospital of Port Jefferson · Kings County Hospital Center · Lenox Hill Hospital · Lincoln Medical &amp; Mental Health Center · Long Island Community Hospital · Long Island Jewish Medical Center · Maimonides Medical Center · Mercy Medical Center · Metropolitan Hospital Center · Montefiore Medical Center · Montefiore Mount Vernon Hospital · Montefiore New Rochelle Hospital · Mount Sinai Beth Israel · Mount Sinai Hospital · Mount Sinai South Nassau · Mount Sinai West · n y Eye and Ear Infirmary · Nassau University Medical Center · New York Community Hospital of Brooklyn, Inc.&nbsp;· New York-Presbyterian Hospital · New York-Presbyterian/Queens · North Shore University Hospital · Northern Westchester Hospital · Nyack Hospital · Nyu Langone Hospitals · Peconic Bay Medical Center · Phelps Hospital · Plainview Hospital · Putnam Hospital Center · Queens Hospital Center · Richmond University Medical Center · South Brooklyn Health · South Shore University Hospital · St Barnabas Hospital · St Catherine of Siena Hospital · St Charles Hospital · St Francis Hospital, Roslyn · St John’s Episcopal Hospital at South Shore · St John’s Riverside Hospital · St Joseph Hospital · St Joseph’s Medical Center · Staten Island University Hospital · Stony Brook University Hospital · Suny Health Science Center at Brooklyn University · Terence Cardinal Cooke Health Care Center · Westchester Medical Center · White Plains Hospital Center · Woodhull Medical &amp; Mental Health Center · Wyckoff Heights Medical Center</td>
</tr>
<tr class="even">
<td style="text-align: left;">Buffalo–Cheektowaga</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Bertrand Chaffee Hospital · Erie County Medical Center · Kaleida Health · Kenmore Mercy Hospital · Mercy Hospital of Buffalo · Mount St Mary’s Hospital and Health Center · Niagara Falls Memorial Medical Center · Sisters of Charity Hospital</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oneonta</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Aurelia Osborn Fox Memorial Hospital · Mary Imogene Bassett Hospital</td>
</tr>
<tr class="even">
<td style="text-align: left;">Batavia</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">United Memorial Medical Center</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cortland</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Guthrie Cortland Regional Medical Center</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massena–Ogdensburg</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Canton-Potsdam Hospital</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>(Source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">Centers for Medicare &amp; Medicaid Services (2026). TEAM participant list.</a>)</p>
</section>
<section id="the-new-yorknewarkjersey-city-cbsa-a-shared-post-acute-market" class="level2">
<h2 class="anchored" data-anchor-id="the-new-yorknewarkjersey-city-cbsa-a-shared-post-acute-market">The New York–Newark–Jersey City CBSA: a shared post-acute market</h2>
<p>The New York–Newark–Jersey City, NY–NJ CBSA is not simply a large metropolitan area — it is a geographically integrated care delivery system in which a patient discharged from a Bronx hospital may recover at a skilled nursing facility in New Jersey, and vice versa. This market integration creates both competitive complexity and coordinating opportunity for TEAM management.</p>
<p>The CBSA contains some of the country’s most well-resourced hospitals. <strong>Hospital for Special Surgery</strong> (HSS) — internationally recognized as the top-ranked orthopedic hospital in the United States — is a TEAM participant, as are NYU Langone (ranked among the top hospitals nationally for orthopedics by U.S. News &amp; World Report), North Shore University Hospital, Lenox Hill Hospital, and Stony Brook University Hospital. These institutions’ historical episode efficiency will influence their target prices; facilities with strong prior CJR performance enter TEAM with tighter targets but also with post-acute coordination infrastructure already in place.</p>
<p>The presence of the NYC Health + Hospitals system — including Bellevue, Kings County, Lincoln Medical, Queens Hospital, Harlem Hospital, Elmhurst, Jacobi, Woodhull, and Metropolitan — introduces a distinct policy dimension. These public hospitals disproportionately serve uninsured and dual-eligible patients, whose post-discharge resources and social determinants of health differ substantially from the commercial patient mix at neighboring academic centers. Under TEAM, risk adjustment partially accounts for patient complexity, but research has consistently found that safety-net hospitals face structural TEAM disadvantages (Navathe et al., 2020).</p>
<p>The large Northwell Health system — which operates North Shore University Hospital, Long Island Jewish Medical Center, South Shore University Hospital, Lenox Hill, Huntington Hospital, Peconic Bay Medical Center, and others — gives it an unusual degree of coordinated leverage under TEAM. Northwell’s ability to direct patients to its own post-acute partners and monitor episode costs across a vertically integrated network is a structural advantage that independent community hospitals in the same CBSA cannot match.</p>
<p>(Source: <a href="https://doi.org/10.1001/jama.2019.19040">Navathe et al.&nbsp;(2020), JAMA 323(2).</a>)</p>
</section>
<section id="buffalo-and-upstate-cbsas" class="level2">
<h2 class="anchored" data-anchor-id="buffalo-and-upstate-cbsas">Buffalo and upstate CBSAs</h2>
<p>Western New York’s <strong>Buffalo–Cheektowaga CBSA</strong> adds eight hospitals, anchored by <strong>Kaleida Health</strong> — the region’s dominant health system operating Buffalo General Medical Center, Women &amp; Children’s Hospital, Gates Vascular Institute, and affiliated facilities — and the <strong>Erie County Medical Center</strong>, the county’s Level 1 trauma center and safety-net hospital. Sisters of Charity Hospital and Mercy Hospital of Buffalo represent the Catholic Health system presence. The smaller community hospitals (Kenmore Mercy, Mount St.&nbsp;Mary’s, Niagara Falls Memorial, Bertrand Chaffee) serve suburban and rural catchment areas with different post-acute landscapes than the urban core.</p>
<p>The three upstate CBSAs — <strong>Oneonta</strong> (Mary Imogene Bassett Hospital and Aurelia Osborn Fox Memorial), <strong>Batavia</strong> (United Memorial Medical Center), and <strong>Cortland</strong> (Guthrie Cortland Regional) — along with <strong>Canton-Potsdam Hospital</strong> in the Massena–Ogdensburg market, represent critical access and rural community hospitals with constrained post-acute networks. For these facilities, TEAM’s 30-day episode window is particularly difficult to manage: skilled nursing facility options are geographically limited, home health capacity is strained, and patients frequently travel significant distances from their county of residence for surgical care, complicating post-discharge follow-up.</p>
</section>
<section id="readmissions-landscape-new-york-under-hrrp" class="level2">
<h2 class="anchored" data-anchor-id="readmissions-landscape-new-york-under-hrrp">Readmissions landscape: New York under HRRP</h2>
<p>Joining the live CMS TEAM roster to the CMS HRRP dataset (9n3s-kdb3, performance period 07/01/2021–06/30/2024) by CCN, 75 of New York’s 78 mandated hospitals appear in the HRRP file. Across those hospitals’ condition pairs, <strong>48.7%</strong> exceed the excess readmission ratio (ERR) threshold of 1.0 — meaning more readmissions than CMS’s risk model predicts. That is essentially in line with the <strong>48.1%</strong> national rate across the same dataset, not the outsized gap sometimes attributed to New York.</p>
<p>The picture varies sharply by condition. New York’s <strong>hip/knee replacement</strong> ERR — the procedure category TEAM weights most heavily — is notably <em>better</em> than the national pattern: 24.4% of NY hip/knee pairs exceed 1.0, versus 47.9% nationally. New York also runs below the national rate on CABG (31.6% vs 49.9%). The state runs <em>above</em> the national rate on the medical conditions HRRP also tracks — heart attack, heart failure, pneumonia, and COPD — all of which sit outside TEAM’s five bundled-payment categories. In short: on the readmission measure most relevant to TEAM specifically, New York’s mandated hospitals outperform the national pool; the state’s readmissions profile looks worse only when medical (non-surgical) conditions are folded into a single blended rate.</p>
<p>Under CMS TEAM, readmissions still carry compounded consequences where they do occur: a patient readmitted within 30 days of a TEAM-qualifying procedure adds both an inpatient cost to the episode total (raising the risk of exceeding the target price) and a separate HRRP penalty event. Managing the first 30 days post-discharge remains the primary lever for TEAM financial performance even where a hospital’s baseline readmission rate is favorable.</p>
<p>(Source: <a href="https://data.cms.gov/provider-data/dataset/9n3s-kdb3">Centers for Medicare &amp; Medicaid Services. HRRP supplemental data, Dataset 9n3s-kdb3.</a> — vendored copy joined to the CMS TEAM participant list by CCN for this report.)</p>
</section>
<section id="financial-exposure-what-this-report-does-and-doesnt-estimate" class="level2">
<h2 class="anchored" data-anchor-id="financial-exposure-what-this-report-does-and-doesnt-estimate">Financial exposure: what this report does and doesn’t estimate</h2>
<p>CMS does not publish hospital-level TEAM episode volumes or target prices in a form this repo can join to the New York roster, so this report does not model a New York-specific episode count, target price, or gain/loss dollar figure — doing so would mean presenting an invented number as if it were New York data. Two external findings are relevant as general context, not as New York-specific estimates:</p>
<ul>
<li>Optum Advisory (2025) estimated that 56% of TEAM-mandated hospitals nationally are projected to lose money once downside risk begins in Performance Year 2, with average losses of $1.2 million per facility. This is a national estimate; Optum’s methodology and hospital-level detail are not published in a form this report can verify or apply to New York specifically.</li>
<li>HFMA (2026) recommends hospitals use Performance Year 1 (2026) — the upside-only year — to establish baseline episode cost data, identify high-cost post-acute partners, and build PCP follow-up protocols before two-sided risk begins in 2027.</li>
</ul>
<p>A hospital that wants a New York-specific dollar estimate needs its own CMS-issued target price file, obtained through the TEAM participant portal — not a state-level average.</p>
<p>(Source: <a href="https://www.hfma.org">Optum Advisory (2025); Healthcare Financial Management Association (2026).</a>)</p>
</section>
<section id="what-new-york-hospitals-must-prioritize-in-2026" class="level2">
<h2 class="anchored" data-anchor-id="what-new-york-hospitals-must-prioritize-in-2026">What New York hospitals must prioritize in 2026</h2>
<ol type="1">
<li><strong>Establish real-time episode cost baselines.</strong> Hospitals must obtain their CMS-issued target price files through the TEAM participant portal and model their current trajectory against those targets before the PY1 reconciliation window closes.</li>
<li><strong>Build or formalize post-acute care networks.</strong> The NYC metro area has hundreds of SNF and home health providers, but their quality and cost profiles vary dramatically. Hospitals should identify preferred post-acute partners whose episode costs align with TEAM targets — a process requiring structured data sharing agreements that take months to negotiate.</li>
<li><strong>Address the 7-day PCP follow-up requirement.</strong> TEAM requires documentation of primary care follow-up within seven days of discharge for qualifying episodes. In New York City, where primary care access is fragmented and PCP shortage areas are common, operationalizing this requirement is a significant workflow challenge for social work and discharge planning teams.</li>
<li><strong>Differentiate Track 2 eligibility.</strong> Safety-net hospitals in the NYC public hospital system — Bellevue, Kings County, Lincoln, Elmhurst, Queens — may qualify for Track 2 (5%/5% stop-gain/stop-loss) given their safety-net designations. Confirming eligibility and electing Track 2 before PY2 may reduce financial volatility for these facilities.</li>
<li><strong>Integrate HRRP and TEAM quality improvement.</strong> New York’s mandated hospitals already run below the national readmission rate on hip/knee replacement specifically, but above it on the medical conditions HRRP tracks. Reducing 30-day readmissions at TEAM procedure types reduces both HRRP penalties and episode costs at once — these programs should be integrated, not operated in parallel — and hospitals should not assume TEAM-specific risk is elevated just because their overall HRRP profile is.</li>
</ol>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently asked questions</h2>
<section id="how-many-hospitals-are-mandated-for-cms-team-in-new-york" class="level3">
<h3 class="anchored" data-anchor-id="how-many-hospitals-are-mandated-for-cms-team-in-new-york">How many hospitals are mandated for CMS TEAM in New York?</h3>
<p>78 hospitals in New York State are mandated to participate in CMS TEAM, based on the March 2026 CMS participant list.</p>
</section>
<section id="which-cbsas-in-new-york-are-included-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="which-cbsas-in-new-york-are-included-in-cms-team">Which CBSAs in New York are included in CMS TEAM?</h3>
<p>Six CBSAs: New York–Newark–Jersey City, NY–NJ (65 hospitals); Buffalo–Cheektowaga, NY (8); Oneonta, NY (2); Batavia, NY (1); Cortland, NY (1); and Massena–Ogdensburg, NY (1).</p>
</section>
<section id="is-hospital-for-special-surgery-required-to-participate-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="is-hospital-for-special-surgery-required-to-participate-in-cms-team">Is Hospital for Special Surgery required to participate in CMS TEAM?</h3>
<p>Yes. Hospital for Special Surgery (HSS) is listed on the CMS TEAM participant roster in the New York–Newark–Jersey City CBSA.</p>
</section>
<section id="is-the-entire-northwell-health-system-mandated" class="level3">
<h3 class="anchored" data-anchor-id="is-the-entire-northwell-health-system-mandated">Is the entire Northwell Health system mandated?</h3>
<p>Several Northwell Health hospitals are on the TEAM participant list, including North Shore University Hospital, Long Island Jewish Medical Center, South Shore University Hospital, Lenox Hill Hospital, Huntington Hospital, and Peconic Bay Medical Center, among others.</p>
</section>
<section id="what-is-new-yorks-hrrp-excess-readmission-rate" class="level3">
<h3 class="anchored" data-anchor-id="what-is-new-yorks-hrrp-excess-readmission-rate">What is New York’s HRRP excess-readmission rate?</h3>
<p>48.7% of New York hospital-condition pairs exceed the ERR 1.0 threshold in the CMS HRRP dataset, versus 48.1% nationally — essentially at parity, not meaningfully worse. On hip/knee replacement specifically, the procedure category TEAM weights most heavily, New York runs <em>below</em> the national rate (24.4% vs 47.9%). HRRP’s “excess readmission ratio” is a risk-adjustment measure, not a payment penalty rate on its own.</p>
</section>
<section id="are-nyc-public-hospitals-health-hospitals-included-in-team" class="level3">
<h3 class="anchored" data-anchor-id="are-nyc-public-hospitals-health-hospitals-included-in-team">Are NYC public hospitals (Health + Hospitals) included in TEAM?</h3>
<p>Yes. Multiple NYC Health + Hospitals facilities are on the TEAM roster, including Bellevue Hospital Center, Kings County Hospital Center, Lincoln Medical Center, Harlem Hospital Center, Elmhurst Hospital Center, Queens Hospital Center, Jacobi Medical Center, and Woodhull Medical Center.</p>
</section>
<section id="when-does-downside-financial-risk-begin-for-new-york-team-hospitals" class="level3">
<h3 class="anchored" data-anchor-id="when-does-downside-financial-risk-begin-for-new-york-team-hospitals">When does downside financial risk begin for New York TEAM hospitals?</h3>
<p>Performance Year 1 (2026) has no downside risk. Most hospitals transition to Track 3 (20%/20% stop-gain/stop-loss) starting in Performance Year 2 (January 1, 2027).</p>
</section>
<section id="does-cms-team-apply-to-upstate-new-york-hospitals" class="level3">
<h3 class="anchored" data-anchor-id="does-cms-team-apply-to-upstate-new-york-hospitals">Does CMS TEAM apply to upstate New York hospitals?</h3>
<p>Yes, but more selectively. CMS chose CBSAs based on regional surgical episode volume. The Buffalo area has 8 mandated hospitals; smaller upstate CBSAs (Oneonta, Batavia, Cortland, Massena-Ogdensburg) each have 1–2 hospitals. The vast majority of the state’s TEAM exposure is concentrated in the NYC metro.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Centers for Medicare &amp; Medicaid Services. (2026). TEAM participant list (March 2026 update). CMMI. https://www.cms.gov/priorities/innovation/innovation-models/team-model</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024, August). Transforming Episode Accountability Model: Final Rule. Federal Register, 89(166), 68986–69178. https://www.federalregister.gov/documents/2024/08/28/2024-17021/medicare-program-hospital-inpatient-prospective-payment-systems</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024). Hospital Readmissions Reduction Program (HRRP) FY2025 supplemental data [Data set]. CMS Provider Data Catalog, Dataset 9n3s-kdb3. https://data.cms.gov/provider-data/dataset/9n3s-kdb3</li>
<li>Dummit, L. A., Kahvecioglu, D., Marrufo, G., Rajkumar, R., Marshall, J., Tan, E., Le, S. T., Terebelo, S., Hearld, L., Xian, Y., Morishima, C., Pittman, P., Barzee, B., &amp; Conway, P. H. (2016). Association between hospital participation in a Medicare bundled payment initiative and payments and quality outcomes for lower extremity joint replacement episodes. JAMA, 316(12), 1267–1278. https://doi.org/10.1001/jama.2016.12717</li>
<li>Finkelstein, A., Ji, Y., Mahoney, N., &amp; Skinner, J. (2021). Mandatory Medicare bundled payment program for lower extremity joint replacement and discharge to institutional postacute care. JAMA, 325(18), 1879–1890. https://doi.org/10.1001/jama.2021.5684</li>
<li>Zuckerman, R. B., Sheingold, S. H., Orav, E. J., Ruhter, J., &amp; Epstein, A. M. (2016). Readmissions, observation, and the Hospital Readmissions Reduction Program. New England Journal of Medicine, 374(16), 1543–1551. https://doi.org/10.1056/NEJMsa1513024</li>
<li>Navathe, A. S., Liao, J. M., Emanuel, E. J., &amp; Press, M. J. (2020). Opening a two-way street for bundled payments. JAMA, 323(2), 121–122. https://doi.org/10.1001/jama.2019.19040</li>
<li>Healthcare Financial Management Association. (2026, March). Hospitals can use 2026 to prepare for CMS TEAM bundled payment risk. HFMA. https://www.hfma.org/payment-reimbursement-and-managed-care/hospitals-can-use-2026-to-prepare-for-cms-team-bundled-payment-risk</li>
<li>Optum Advisory. (2025, November). What hospitals need to know about TEAM for 2026. Advisory.com. https://www.advisory.com/topics/policy-and-payment/hospitals-need-to-know-team</li>
</ol>
<div class="wp-disclaimer">
<p><strong>Disclaimer.</strong> Rainfall Health is not a hospital, health system, or health care provider. This paper is prepared by health care industry professionals, not clinicians, and does not constitute clinical, legal, financial, or regulatory advice. Roster counts and readmission figures are computed from the CMS files cited above; this paper does not assess, rate, or make claims about the quality of care provided by any individual hospital or organization.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="scripts/listen-along.js" defer=""></script>
<script src="scripts/highlight-notes.js" defer=""></script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>