<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ahmed Qureshi, Founder &amp; Chief Executive Officer, Rainfall Health">
<meta name="dcterms.date" content="2026-09-01">
<meta name="description" content="California holds the largest state roster in CMS’s Transforming Episode Accountability Model. An analysis of where the mandate sits, how participating hospitals perform on readmissions today, and what changes in Performance Year 2.">

<title>CMS TEAM in California: Reading the State’s Roster, Risk and Readiness – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


<link rel="stylesheet" href="../../styles/report.css">
<link rel="stylesheet" href="../../styles/stratus-media.css">
<link rel="stylesheet" href="styles/report.css">
<meta property="og:title" content="CMS TEAM in California: Reading the State’s Roster, Risk and Readiness">
<meta property="og:description" content="California holds the largest state roster in CMS’s Transforming Episode Accountability Model. What the data shows, and what changes in Performance Year 2.">
<meta property="og:image" content="assets/rainfall-logo.png">
<meta property="og:site_name" content="Stratus">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="CMS TEAM in California: Reading the State’s Roster, Risk and Readiness">
<meta name="twitter:description" content="California holds the largest state roster in CMS’s Transforming Episode Accountability Model. What the data shows, and what changes in Performance Year 2.">
<meta name="twitter:image" content="assets/rainfall-logo.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">01 · At a glance</a></li>
  <li><a href="#where-the-mandate-sits" id="toc-where-the-mandate-sits" class="nav-link" data-scroll-target="#where-the-mandate-sits">02 · Where the mandate sits</a>
  <ul class="collapse">
  <li><a href="#figure-1-participating-hospitals-by-cbsa" id="toc-figure-1-participating-hospitals-by-cbsa" class="nav-link" data-scroll-target="#figure-1-participating-hospitals-by-cbsa">Figure 1 · Participating hospitals by CBSA</a></li>
  <li><a href="#figure-2-participating-hospitals-by-region" id="toc-figure-2-participating-hospitals-by-region" class="nav-link" data-scroll-target="#figure-2-participating-hospitals-by-region">Figure 2 · Participating hospitals by region</a></li>
  </ul></li>
  <li><a href="#readmission-performance-where-team-pays" id="toc-readmission-performance-where-team-pays" class="nav-link" data-scroll-target="#readmission-performance-where-team-pays">03 · Readmission performance where TEAM pays</a>
  <ul class="collapse">
  <li><a href="#figure-3-mean-excess-readmission-ratio-by-condition" id="toc-figure-3-mean-excess-readmission-ratio-by-condition" class="nav-link" data-scroll-target="#figure-3-mean-excess-readmission-ratio-by-condition">Figure 3 · Mean Excess Readmission Ratio by condition</a></li>
  <li><a href="#figure-4-share-of-hospitals-above-the-expectation-line" id="toc-figure-4-share-of-hospitals-above-the-expectation-line" class="nav-link" data-scroll-target="#figure-4-share-of-hospitals-above-the-expectation-line">Figure 4 · Share of hospitals above the expectation line</a></li>
  </ul></li>
  <li><a href="#what-changes-in-performance-year-2" id="toc-what-changes-in-performance-year-2" class="nav-link" data-scroll-target="#what-changes-in-performance-year-2">04 · What changes in Performance Year 2</a></li>
  <li><a href="#considerations-for-hospital-leadership" id="toc-considerations-for-hospital-leadership" class="nav-link" data-scroll-target="#considerations-for-hospital-leadership">05 · Considerations for hospital leadership</a></li>
  <li><a href="#methods-sources-and-limitations" id="toc-methods-sources-and-limitations" class="nav-link" data-scroll-target="#methods-sources-and-limitations">06 · Methods, sources, and limitations</a></li>
  <li><a href="#about-rainfall-health" id="toc-about-rainfall-health" class="nav-link" data-scroll-target="#about-rainfall-health">07 · About Rainfall Health</a></li>
  <li><a href="#appendix-a-glossary" id="toc-appendix-a-glossary" class="nav-link" data-scroll-target="#appendix-a-glossary">Appendix A · Glossary</a></li>
  <li><a href="#appendix-b-data-companion" id="toc-appendix-b-data-companion" class="nav-link" data-scroll-target="#appendix-b-data-companion">Appendix B · Data companion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CMS TEAM in California: Reading the State’s Roster, Risk and Readiness</h1>
</div>

<div>
  <div class="description">
    California holds the largest state roster in CMS’s Transforming Episode Accountability Model. An analysis of where the mandate sits, how participating hospitals perform on readmissions today, and what changes in Performance Year 2.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ahmed Qureshi, Founder &amp; Chief Executive Officer, Rainfall Health </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="wp-cover">
<p><img src="assets/rainfall-logo.png" class="wp-logo img-fluid"></p>
<p class="wp-kicker">
White paper
</p>
<section id="cms-team-in-california-reading-the-states-roster-risk-and-readiness" class="level1">
<h1>CMS TEAM in California: Reading the State’s Roster, Risk and Readiness</h1>
<p class="wp-dek">
107 participating hospitals · 11 CBSAs · Performance Year 2 begins January 2027
</p>
<p class="wp-meta">
Ahmed Qureshi, Founder &amp; Chief Executive Officer, Rainfall Health · September 2026<br>What California’s TEAM roster and current CMS performance data show about hospital readiness — and what changes in Performance Year 2.
</p>
</section>
</div>
<div class="wp-listen-card">
<audio id="wp-audio" src="audio/california-narration.mp3" preload="metadata">
</audio>
<div class="wp-listen-panel">
<div class="wp-listen-grid">
<div class="wp-listen-main">
<p class="wp-listen-kicker">
Rainfall white paper · Narration
</p>
<p class="wp-listen-title">
Listen while you read
</p>
<div class="wp-listen-toolbar">
<button type="button" class="wp-play" data-action="play-pause" aria-label="Play" aria-pressed="false">
<span class="wp-play-glyph" aria-hidden="true"></span>
</button>
<button type="button" class="wp-icon-btn" data-action="back-15" aria-label="Back 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M9 7v4H4l5 5V7z"></path><path d="M13 7a5 5 0 1 1 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<button type="button" class="wp-icon-btn wp-speed-btn" data-action="speed-dial" aria-label="Playback speed 1×">
<span data-role="speed-label">1×</span>
</button>
<button type="button" class="wp-icon-btn" data-action="forward-15" aria-label="Forward 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M15 7v4h5l-5 5V7z"></path><path d="M11 7a5 5 0 1 0 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<p><span class="wp-time" aria-live="polite"><span data-role="time-current">00:00</span> / <span data-role="time-duration">00:00</span></span></p>
</div>
<p><input type="range" class="wp-seek" data-action="seek" min="0" max="100" value="0" step="0.1" aria-label="Seek"></p>
</div>
</div>
</div>
</div>
<div class="wp-action-bar">
<p><a class="wp-action" href="california.pdf">Download PDF</a> <a class="wp-action" href="california-narration.txt" download="california-narration.txt">Narration script</a> <a class="wp-action" href="#appendix-b-data-companion">Data companion</a></p>
</div>
<div class="wp-in-brief callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>In brief.</strong> California carries 107 of the 720 hospitals in the Transforming Episode Accountability Model — the largest state roster in the country, about 14.9% of the national list. Exposure is concentrated in a handful of metro markets, not spread evenly across the state. On readmissions, California’s position depends entirely on which condition you look at: surgical cohorts that map to TEAM look stronger than the national average, and every medical condition tracked runs the other way. That split starts counting for more in Performance Year 2, when a hospital-wide readmission measure enters the quality score.</p>
</div>
</div>
</div>
<section id="at-a-glance" class="level1">
<h1>01 · At a glance</h1>
<p>California carries the largest state roster in the country’s newest mandatory hospital payment program. When the Centers for Medicare and Medicaid Services built the list of hospitals required to join the Transforming Episode Accountability Model, known as TEAM, it put <strong>107 of them in California</strong>, spread across <strong>11 metropolitan markets</strong>, out of <strong>720 hospitals nationwide</strong>. That’s close to <strong>14.9%</strong> of the entire national roster sitting inside one state. Of California’s <strong>107</strong>, <strong>106 were mandated in</strong>. Only <strong>1 joined voluntarily</strong>. All of them are locked in for the model’s full run, <strong>January 1, 2026 – December 31, 2030</strong>.</p>
<p>It’s worth pausing on what TEAM actually asks of a hospital, because it’s a real departure from how Medicare used to pay for surgery. The old model paid piece by piece: a fee for the operation, a separate fee for the hospital stay, and then whatever came after — a stay in a skilled nursing facility, home health visits, or a return trip to the emergency room — billed and reimbursed on its own. TEAM collapses all of that into one <strong>30-day window</strong>. A hospital is now accountable, financially, for everything that happens to a patient for thirty days after five kinds of procedures: hip and knee replacement, spinal fusion, coronary bypass, surgical repair of a hip fracture, and major bowel surgery. Spend too much across that window, or let the patient come back in, and it’s the hospital’s number that moves, not some other part of the system’s.</p>
</section>
<section id="where-the-mandate-sits" class="level1">
<h1>02 · Where the mandate sits</h1>
<p>Start with geography, because California’s exposure is not spread evenly across the state — it’s concentrated in a handful of places. The <strong>San Francisco–Oakland–Fremont</strong> market alone accounts for <strong>37 hospitals</strong>, about <strong>35%</strong> of the state’s total, and that makes it the <strong>2nd-largest TEAM market in the entire country</strong>, behind only New York. <strong>Riverside–San Bernardino–Ontario</strong>, the Inland Empire, comes in at <strong>30 hospitals</strong>, <strong>28%</strong> of the state, and ranks <strong>4th nationally</strong>. <strong>San Diego–Chula Vista–Carlsbad</strong> adds another <strong>15</strong>, about <strong>14%</strong>. The remaining markets are smaller; the charts below show every CBSA and how Rainfall groups them into regions.</p>
<p>There’s also a system-ownership story worth knowing before you get to the performance data. About <strong>64%</strong> of California’s roster — <strong>68 of the 107 hospitals</strong> — sits in <strong>14 multi-hospital systems</strong> with at least two TEAM sites in the state, and the single largest, <strong>Kaiser Permanente</strong>, accounts for <strong>17 hospitals</strong> on its own, about <strong>16%</strong> of the entire state roster. When one system holds a double-digit share of a state’s participants, decisions about episode standards, post-acute contracting, and data infrastructure tend to get made centrally, which changes who actually needs to be in the room when a hospital plans its TEAM readiness.</p>
<section id="figure-1-participating-hospitals-by-cbsa" class="level2">
<h2 class="anchored" data-anchor-id="figure-1-participating-hospitals-by-cbsa">Figure 1 · Participating hospitals by CBSA</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal bar chart of TEAM hospitals by California CBSA, led by San Francisco-Oakland-Fremont">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="california_files/figure-html/fig-cbsa-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Horizontal bar chart of TEAM hospitals by California CBSA, led by San Francisco-Oakland-Fremont">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: California TEAM participating hospitals by CBSA. Source: CMS TEAM participant list (CMS, 2026b). | Rainfall Health analysis | rainfallhealth.com
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="figure-2-participating-hospitals-by-region" class="level2">
<h2 class="anchored" data-anchor-id="figure-2-participating-hospitals-by-region">Figure 2 · Participating hospitals by region</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal bar chart of TEAM hospitals by California region, led by the Bay Area and Inland Empire">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="california_files/figure-html/fig-region-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Horizontal bar chart of TEAM hospitals by California region, led by the Bay Area and Inland Empire">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: California TEAM hospitals by region. Bay Area combines San Francisco–Oakland–Fremont and San Jose–Sunnyvale–Santa Clara; Inland Empire is Riverside–San Bernardino–Ontario. Source: CMS TEAM participant list (CMS, 2026b), grouped by Rainfall Health. | Rainfall Health analysis | rainfallhealth.com
</figcaption>
</figure>
</div>
</div>
</div>
<p>Grouping those markets into regions sharpens the picture further. The <strong>Bay Area</strong> holds <strong>43 hospitals</strong>, about <strong>40%</strong> of the state. The <strong>Inland Empire</strong> holds <strong>30</strong>, <strong>28%</strong>. <strong>Greater Los Angeles</strong>, despite being the state’s largest metro area by population, contributes <strong>a single hospital</strong> to the entire list — the clearest illustration that CMS built TEAM around specific metropolitan statistical areas, not around where the most hospitals happen to be.</p>
</section>
</section>
<section id="readmission-performance-where-team-pays" class="level1">
<h1>03 · Readmission performance where TEAM pays</h1>
<p>Now to the part of the analysis that actually predicts how these hospitals are likely to fare under the model: readmissions. Medicare publishes an <strong>excess readmission ratio</strong> for nearly every hospital in the country, condition by condition. It compares how many patients actually came back within thirty days against how many you’d expect, given that hospital’s specific mix of patients. A ratio under one means fewer readmissions than expected. Over one means more. Because TEAM pays hospitals based on the thirty-day arc after surgery, a hospital’s existing readmission pattern is about the closest thing available to a preview of how it will perform under the new rules.</p>
<p>This analysis matched all <strong>107 California hospitals</strong> to Medicare’s public readmissions file using their federal certification numbers, so the linkage is exact, hospital by hospital. <strong>96 of the 107</strong> have at least one reportable ratio in the current file; the other <strong>11</strong> fall below Medicare’s minimum case-volume threshold across every condition tracked. The data covers <strong>July 2021 – June 2024</strong>.</p>
<section id="figure-3-mean-excess-readmission-ratio-by-condition" class="level2">
<h2 class="anchored" data-anchor-id="figure-3-mean-excess-readmission-ratio-by-condition">Figure 3 · Mean Excess Readmission Ratio by condition</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-err" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Paired dot chart comparing mean excess readmission ratios by condition, California versus national">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-err-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="california_files/figure-html/fig-err-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Paired dot chart comparing mean excess readmission ratios by condition, California versus national">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-err-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Mean Excess Readmission Ratio by condition, California TEAM hospitals compared with the national average. Measurement window: July 2021 – June 2024. Source: CMS HRRP public use file, dataset 9n3s-kdb3 (CMS, 2026c). | Rainfall Health analysis | rainfallhealth.com
</figcaption>
</figure>
</div>
</div>
</div>
<p>Here’s where the story gets genuinely interesting, because California’s position depends entirely on which condition you’re looking at. On the two surgical categories that map most directly onto what TEAM actually pays for — hip and knee replacement and coronary bypass — California <strong>outperforms the nation</strong>. The average ratio for joint replacement across California’s TEAM hospitals is <strong>0.980</strong>, against <strong>1.004 nationally</strong>. Bypass surgery comes in at <strong>0.993</strong> against <strong>1.002 nationally</strong>. Both numbers sit on the favorable side of the line.</p>
<p>But shift to the medical conditions — the ones that aren’t part of TEAM’s five surgical categories but draw on the same hospital floors, the same discharge planners, and the same post-acute partners — and the pattern flips. Heart attack patients in California come back at a ratio of <strong>1.008</strong> against <strong>1.002 nationally</strong>. Heart failure runs <strong>1.006</strong> against <strong>1.001</strong>. Pneumonia is the widest gap of all: <strong>1.014</strong> in California against <strong>1.001 nationally</strong>. COPD is close to even, <strong>1.002</strong> against <strong>1.001</strong>. On every one of these medical conditions, California hospitals are readmitting more patients than their case mix would predict, while the rest of the country is essentially running right at expectation.</p>
<p><strong>Takeaway:</strong> California looks stronger on the surgical readmissions that map most directly to TEAM episodes, but hotter on medical readmissions statewide — so a hospital cannot assume its joint-replacement or bypass performance covers the rest of the house.</p>
</section>
<section id="figure-4-share-of-hospitals-above-the-expectation-line" class="level2">
<h2 class="anchored" data-anchor-id="figure-4-share-of-hospitals-above-the-expectation-line">Figure 4 · Share of hospitals above the expectation line</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-err-prevalence" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Grouped bar chart of the share of hospitals above an excess readmission ratio of 1.00, by condition">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-err-prevalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="california_files/figure-html/fig-err-prevalence-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Grouped bar chart of the share of hospitals above an excess readmission ratio of 1.00, by condition">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-err-prevalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Share of hospitals with an Excess Readmission Ratio above 1.00, by condition, California compared with national. Source: CMS HRRP public use file, dataset 9n3s-kdb3 (CMS, 2026c). | Rainfall Health analysis | rainfallhealth.com
</figcaption>
</figure>
</div>
</div>
</div>
<p>It’s also worth knowing that these averages hide as much as they reveal. California’s strong joint-replacement number isn’t a story of uniform excellence — it’s a story of standout performers pulling the average down. <strong>49%</strong> of California’s reporting hospitals are still sitting above the expected line on joint replacement, almost identical to <strong>48% nationally</strong>, even though the state average looks meaningfully better. Bypass surgery is the one place where the spread genuinely favors California: only <strong>42%</strong> of hospitals sit above the line, against <strong>50% nationally</strong>. On the medical side, the spread confirms the averages: <strong>57%</strong> of California hospitals exceed expectation on heart attack and <strong>57%</strong> on pneumonia, against <strong>50%</strong> and <strong>47% nationally</strong>. Heart failure sits at <strong>54%</strong> against <strong>49%</strong>, and COPD at <strong>49%</strong> against <strong>47%</strong>.</p>
<p><strong>For your hospital, the number that matters is the excess readmission ratio tied to your CMS certification number in Medicare’s public file — not California’s average.</strong> The statewide figures tell you almost nothing about where you stand; your CCN-level ratios are already public. Condition-level detail is in the data companion CSVs in Appendix B if you want to work from files rather than the charts above.</p>
</section>
</section>
<section id="what-changes-in-performance-year-2" class="level1">
<h1>04 · What changes in Performance Year 2</h1>
<p>That split between surgical and medical performance matters more starting next year than it did this year, because the scoring itself is about to change. TEAM’s first performance year leaned in part on a patient-safety composite measure that CMS is retiring after year one. From Performance Year 2 onward, the quality score instead draws on a broader <strong>hospital-wide, all-cause readmission measure</strong>, plus two new patient-harm measures covering falls with injury and postoperative respiratory failure, plus a measure tracking risk-standardized death among surgical patients who develop complications. The existing patient-reported outcome measure for hip and knee replacement continues, and a new measure tracking information transfer between care settings joins in year three, specific to joint replacement and spinal fusion episodes. The hospital-wide readmission measure is the one to watch, because unlike the outgoing safety composite, it does not distinguish between a surgical patient and a medical one. It counts everyone. That’s precisely the measure where California’s medical-condition weakness is going to show up, at the exact moment it starts counting more toward the score.</p>
<p>In plain terms: starting in Performance Year 2, CMS blends <strong>all</strong> of a hospital’s readmissions into one hospital-wide score — not just the surgical patients TEAM pays for directly. California’s TEAM hospitals look relatively strong on hip/knee and bypass readmissions, but <strong>above</strong> national expectation on the medical conditions in this file. A hospital that is fine on surgery can still see that broader measure pull its <strong>composite quality score</strong> down when it starts counting in reconciliation — without any change in how strong the surgical averages look on their own.</p>
<p>A few other pieces are already locked in. Spinal fusion has been one of TEAM’s five procedure categories from the start, but the definition is expanding: three new diagnosis-related-group codes for extensive and complex spinal fusion procedures take effect for discharges on or after <strong>October 1, 2026</strong>, and they fold directly into TEAM’s existing spinal fusion category. Any hospital that hasn’t updated its coding and documentation workflows for that change will feel it the first time reconciliation runs. Separately, the way Medicare calculates target prices is being recalibrated. Starting in Performance Year 2, the normalization factor that adjusts those prices will be calculated across a full three-year baseline instead of just the most recent year, alongside updated risk-adjustment coefficients, which should smooth out some of the volatility hospitals saw in year one.</p>
<p>There’s also a change worth knowing about even for hospitals convinced TEAM is their only concern. Washington finalized a second, entirely separate mandatory bundled-payment program for joint replacement specifically, covering nearly every acute-care hospital in the country that isn’t already in TEAM. It takes effect <strong>January 1, 2028</strong>, and it explicitly excludes hospitals already participating in TEAM. The practical effect is that California’s <strong>107 TEAM hospitals</strong> will keep operating on a <strong>30-day episode window</strong> all the way through <strong>2030</strong>, while most of their peers elsewhere in the state and the country shift onto a <strong>90-day window</strong> that also reaches into outpatient procedures and adds ankle replacement to the covered list. That’s two genuinely different playbooks running side by side — worth remembering the next time a joint-replacement strategy gets compared across a system that operates in both worlds, or gets evaluated as part of an acquisition.</p>
</section>
<section id="considerations-for-hospital-leadership" class="level1">
<h1>05 · Considerations for hospital leadership</h1>
<p>So what should an executive actually do with all of this? Start by confirming your own hospital’s status using its <strong>federal certification number</strong> rather than its name, because names drift between internal systems and Medicare’s files in ways that can create real confusion about who’s actually on the list and on what terms. Pull your own condition-level readmission ratios directly, because the statewide pattern — as strong as it is on surgery and as weak as it is on medical conditions — tells you almost nothing about where any one hospital stands. Start extending the discipline that’s clearly working in surgical discharge planning over to medical admissions, because that’s exactly where the scoring is about to lean harder. Revisit post-acute routing decisions using the actual evidence rather than habits inherited from older programs, now that the expanded three-day skilled-nursing waiver gives more room to do that deliberately. And calibrate expectations to what the evidence actually shows rather than to the model’s own ambition: real, durable savings are possible, but they come from sustained change in post-acute patterns over time, not from a single strong quarter.</p>
</section>
<section id="methods-sources-and-limitations" class="level1">
<h1>06 · Methods, sources, and limitations</h1>
<div class="cell">
<div id="tbl-methods" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-methods-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-methods-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 54%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: left;">Basis</th>
<th style="text-align: left;">Computed or cited</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Roster counts and CBSA breakdown</td>
<td style="text-align: left;">TEAM Participant List - 2026Q2 (as of April 15, 2026), parsed and vendored to the repository</td>
<td style="text-align: left;">Computed at render time</td>
</tr>
<tr class="even">
<td style="text-align: left;">National TEAM hospital total</td>
<td style="text-align: left;">Same vendored participant list (720 hospitals nationwide)</td>
<td style="text-align: left;">Computed at render time</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Readmission analysis</td>
<td style="text-align: left;">CMS HRRP public use file (dataset 9n3s-kdb3), window July 2021 – June 2024</td>
<td style="text-align: left;">Computed at render time</td>
</tr>
<tr class="even">
<td style="text-align: left;">Roster-to-HRRP linkage</td>
<td style="text-align: left;">CMS Certification Number, exact match</td>
<td style="text-align: left;">96 of 107 hospitals carry reportable data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Multi-hospital system concentration</td>
<td style="text-align: left;">CCN map in data/ca_team_system_affiliations.csv (name-to-system, Sept 2026 review)</td>
<td style="text-align: left;">Computed at render time</td>
</tr>
<tr class="even">
<td style="text-align: left;">Policy and rule changes</td>
<td style="text-align: left;">Federal Register final rules and 42 CFR 512.547</td>
<td style="text-align: left;">Cited</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bundled payment evidence</td>
<td style="text-align: left;">Peer-reviewed evaluations of CJR and BPCI</td>
<td style="text-align: left;">Cited</td>
</tr>
<tr class="even">
<td style="text-align: left;">Episode-cost exposure</td>
<td style="text-align: left;">Not published at hospital level</td>
<td style="text-align: left;">Not presented</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>One thing this analysis deliberately does not do is put a dollar figure on any of this. Medicare doesn’t publish what an individual hospital’s target price is, or what its baseline episode spending looks like, and without that, any specific dollar exposure number circulating for California is somebody’s estimate dressed up as a fact. What the evidence does support, from Medicare’s own evaluations of earlier bundled-payment efforts, is a rough sense of where the money actually moves. In the first year of the mandatory joint-replacement program that preceded TEAM, hospitals under the mandate cut the share of patients discharged to institutional post-acute care by <strong>2.9 percentage points</strong>, but total Medicare spending per episode didn’t change by a statistically meaningful amount. A separate, longer-running voluntary bundled-payment program did show real savings over time, roughly <strong>$1,166 less per episode</strong> compared to hospitals outside the program, driven again mostly from reduced use of institutional post-acute care rather than from cutting anything in the hospital stay itself, and without a measurable increase in readmissions, emergency visits, or deaths. The lesson for California is that savings are achievable, but they show up gradually, through sustained changes in where patients go after discharge, not in the first reconciliation cycle.</p>
<p>Every number quoted in Sections 01 through 05 is computed at render time from the vendored CMS participant list and HRRP public use file (July 2021 – June 2024). The national TEAM total (720 hospitals) is the row count of that same participant file, not a separate CMS headline figure. <strong>Counts are parsed from TEAM Participant List - 2026Q2 (as of April 15, 2026) (source: https://www.cms.gov/team-model-participant-list, retrieved 2026-09-21) and yield a California total of 107: San Francisco–Oakland–Fremont 37, Riverside–San Bernardino–Ontario 30, Bay Area plus Inland Empire 73 (68%). These reconcile to the editorial anchors held for this report. CMS republishes the list quarterly, so counts should always be read with their list vintage.</strong> This copy was built on <strong>October 6, 2026</strong>. Full citations, glossary, and downloadable tables are in the appendices below.</p>
</section>
<section id="about-rainfall-health" class="level1">
<h1>07 · About Rainfall Health</h1>
<p>Rainfall Health is an AI-powered accountability and accessibility platform built for Medicare-mandated models, including TEAM and CJR-X. The platform is organized around three functions: automating compliance against what CMS actually requires, supporting case management and care coordination across the post-acute window where much of an episode’s cost sits, and enabling care design at the episode level. Rainfall Health is a health care technology company, not a hospital, health system, or provider organization.</p>
<p>This paper is part of an ongoing series analyzing how the TEAM mandate is distributed across states and markets, using published CMS data.</p>
<p><strong>To discuss what this means for a specific hospital or system</strong>, contact Jessica Ohlssen, Senior Vice President of Revenue, at <a href="mailto:johlssen@rainfallhealth.com">johlssen@rainfallhealth.com</a>. Jessica leads go-to-market strategy and hospital partnerships at Rainfall Health and brings more than sixteen years in value-based care, including roles as Head of Provider Market at Unite Us and leadership of business development and partnerships at Manifest MedEx. She holds a B.Sc. in Psychology and Chemistry from DePaul University and an M.S. in Urban Policy and Public Health from The New School.</p>
<p>Further reading on the model is available at <a href="https://www.rainfallhealth.com/cms-team/">rainfallhealth.com/cms-team</a>.</p>
</section>
<section id="appendix-a-glossary" class="level1">
<h1>Appendix A · Glossary</h1>
<div class="cell">
<div id="tbl-glossary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-glossary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-glossary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 91%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CBSA</td>
<td style="text-align: left;">Core-Based Statistical Area. The federal metropolitan-area unit CMS used to select hospitals for mandatory TEAM participation.</td>
</tr>
<tr class="even">
<td style="text-align: left;">CCN</td>
<td style="text-align: left;">CMS Certification Number. The unique federal identifier for a hospital; stable across name changes and the key used to link datasets in this analysis.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CJR-X</td>
<td style="text-align: left;">Comprehensive Care for Joint Replacement Expanded Model. A nationwide mandatory 90-day joint replacement model beginning January 1, 2028, which excludes hospitals participating in TEAM.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite Quality Score</td>
<td style="text-align: left;">The quality score CMS applies to a TEAM participant’s reconciliation, built from a defined set of quality measures that changes between performance years.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ERR</td>
<td style="text-align: left;">Excess Readmission Ratio. A hospital’s predicted 30-day readmissions divided by its expected readmissions, given its case mix. Above 1.00 is more than expected; below 1.00 is fewer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">HCC</td>
<td style="text-align: left;">Hierarchical Condition Category. The risk-adjustment framework CMS uses to account for patient complexity; TEAM adopted version 28 beginning in 2026.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HRRP</td>
<td style="text-align: left;">Hospital Readmissions Reduction Program. The Medicare program that publishes the condition-level readmission data used in Section 03.</td>
</tr>
<tr class="even">
<td style="text-align: left;">IPPS</td>
<td style="text-align: left;">Inpatient Prospective Payment System. The Medicare payment system for acute care hospital inpatient stays, and the annual rule vehicle through which TEAM is updated.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MS-DRG</td>
<td style="text-align: left;">Medicare Severity Diagnosis-Related Group. The classification that determines inpatient payment and, in TEAM, which procedures trigger an episode.</td>
</tr>
<tr class="even">
<td style="text-align: left;">SNF three-day rule</td>
<td style="text-align: left;">The Medicare requirement of a qualifying three-day inpatient stay before covered skilled nursing facility care. TEAM waives it under defined conditions, widening post-acute routing options.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TEAM</td>
<td style="text-align: left;">Transforming Episode Accountability Model. A five-year mandatory Medicare model running January 1, 2026 through December 31, 2030, holding hospitals accountable for cost and quality across a 30-day window following five surgical episode categories.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="appendix-b-data-companion" class="level1">
<h1>Appendix B · Data companion</h1>
<p>CSV files (regenerated each render) back every figure and include the full participant directory:</p>
<div class="cell">
<div id="tbl-companion" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-companion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-companion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 58%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">File</th>
<th style="text-align: left;">Contents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="data-companion/ca-team-err-by-condition.csv" download="">ca-team-err-by-condition.csv</a></td>
<td style="text-align: left;">Condition-level mean ERR and share above 1.00, California and national</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="data-companion/ca-team-hospitals-by-cbsa.csv" download="">ca-team-hospitals-by-cbsa.csv</a></td>
<td style="text-align: left;">CBSA-level hospital counts and share of the state roster</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="data-companion/ca-team-hospitals-by-region.csv" download="">ca-team-hospitals-by-region.csv</a></td>
<td style="text-align: left;">Regional hospital counts and share of the state roster</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="data-companion/ca-team-participant-directory.csv" download="">ca-team-participant-directory.csv</a></td>
<td style="text-align: left;">Full participant directory: hospital, CCN, CBSA, participation basis, dates</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="data-companion/ca-team-system-affiliations.csv" download="">ca-team-system-affiliations.csv</a></td>
<td style="text-align: left;">CCN-to-system map used for Section 02 concentration counts</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="references" class="level1">
<h1>References</h1>
<span id="ref-roster-label" hidden="">TEAM Participant List - 2026Q2 (as of April 15, 2026)</span>
<div id="ref-hub" class="ref-hub" aria-busy="true">

</div>
<div class="wp-disclaimer">
<p><strong>Disclaimer.</strong> Rainfall Health is not a hospital, health system, or health care provider. This paper is prepared by health care industry professionals, not clinicians, and does not constitute clinical, legal, financial, or regulatory advice. Roster counts and readmission figures are computed from the CMS files cited above; this paper does not assess, rate, or make claims about the quality of care provided by any individual hospital or organization.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="scripts/listen-along.js" defer=""></script>
<script src="scripts/highlight-notes.js" defer=""></script>
<script src="scripts/references-ui.js" defer=""></script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>