<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jennifer Tim-Diamond for Rainfall Health">
<meta name="dcterms.date" content="2026-09-01">
<meta name="description" content="Florida’s 40 TEAM-mandated hospitals post a real, sizable readmissions gap versus the national rate — but not the one the original headline claimed. Verified against live CMS data, including the heart-attack readmissions gap that turns out to be the state’s actual outlier finding.">

<title>CMS TEAM in Florida: 40 Mandated Hospitals Across 11 Markets, from Jacksonville to the Keys – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">


<link rel="stylesheet" href="../../styles/report.css">
<link rel="stylesheet" href="../../styles/stratus-media.css">
<link rel="stylesheet" href="styles/report.css">
<meta property="og:title" content="CMS TEAM in Florida: 40 Mandated Hospitals Across 11 Markets, from Jacksonville to the Keys">
<meta property="og:description" content="Florida’s 40 TEAM-mandated hospitals post a real, sizable readmissions gap versus the national rate — verified against live CMS data, including the heart-attack readmissions gap that is the state’s actual outlier finding.">
<meta property="og:image" content="assets/rainfall-logo.png">
<meta property="og:site_name" content="Stratus">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="CMS TEAM in Florida: 40 Mandated Hospitals Across 11 Markets, from Jacksonville to the Keys">
<meta name="twitter:description" content="Florida’s 40 TEAM-mandated hospitals post a real, sizable readmissions gap versus the national rate — verified against live CMS data.">
<meta name="twitter:image" content="assets/rainfall-logo.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">01 · At a glance</a></li>
  <li><a href="#where-the-mandate-sits" id="toc-where-the-mandate-sits" class="nav-link" data-scroll-target="#where-the-mandate-sits">02 · Where the mandate sits</a></li>
  <li><a href="#guide-narrative-from-the-website-team-report" id="toc-guide-narrative-from-the-website-team-report" class="nav-link" data-scroll-target="#guide-narrative-from-the-website-team-report">03 · Guide narrative (from the website TEAM report)</a>
  <ul class="collapse">
  <li><a href="#floridas-team-mandate-scale-geography-and-demographic-stakes" id="toc-floridas-team-mandate-scale-geography-and-demographic-stakes" class="nav-link" data-scroll-target="#floridas-team-mandate-scale-geography-and-demographic-stakes">Florida’s TEAM mandate: scale, geography, and demographic stakes</a></li>
  <li><a href="#jacksonville-floridas-largest-team-market" id="toc-jacksonville-floridas-largest-team-market" class="nav-link" data-scroll-target="#jacksonville-floridas-largest-team-market">Jacksonville: Florida’s largest TEAM market</a></li>
  <li><a href="#adventhealth-and-hca-system-dominance-in-florida-team-markets" id="toc-adventhealth-and-hca-system-dominance-in-florida-team-markets" class="nav-link" data-scroll-target="#adventhealth-and-hca-system-dominance-in-florida-team-markets">AdventHealth and HCA: system dominance in Florida TEAM markets</a></li>
  <li><a href="#small-market-and-rural-hospitals-the-panhandle-and-south-florida" id="toc-small-market-and-rural-hospitals-the-panhandle-and-south-florida" class="nav-link" data-scroll-target="#small-market-and-rural-hospitals-the-panhandle-and-south-florida">Small-market and rural hospitals: the Panhandle and South Florida</a></li>
  <li><a href="#complete-hospital-directory-by-cbsa" id="toc-complete-hospital-directory-by-cbsa" class="nav-link" data-scroll-target="#complete-hospital-directory-by-cbsa">Complete hospital directory by CBSA</a></li>
  <li><a href="#readmissions-and-team-financial-exposure-in-florida" id="toc-readmissions-and-team-financial-exposure-in-florida" class="nav-link" data-scroll-target="#readmissions-and-team-financial-exposure-in-florida">Readmissions and TEAM financial exposure in Florida</a></li>
  <li><a href="#what-this-analysis-does-not-estimate" id="toc-what-this-analysis-does-not-estimate" class="nav-link" data-scroll-target="#what-this-analysis-does-not-estimate">What this analysis does not estimate</a></li>
  <li><a href="#frequently-asked-questions" id="toc-frequently-asked-questions" class="nav-link" data-scroll-target="#frequently-asked-questions">Frequently asked questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CMS TEAM in Florida: 40 Mandated Hospitals Across 11 Markets, from Jacksonville to the Keys</h1>
</div>

<div>
  <div class="description">
    Florida’s 40 TEAM-mandated hospitals post a real, sizable readmissions gap versus the national rate — but not the one the original headline claimed. Verified against live CMS data, including the heart-attack readmissions gap that turns out to be the state’s actual outlier finding.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jennifer Tim-Diamond for Rainfall Health </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="wp-cover">
<p><img src="assets/rainfall-logo.png" class="wp-logo img-fluid"></p>
<p class="wp-kicker">
White paper
</p>
<section id="cms-team-in-florida-40-mandated-hospitals-across-11-markets-from-jacksonville-to-the-keys" class="level1">
<h1>CMS TEAM in Florida: 40 Mandated Hospitals Across 11 Markets, from Jacksonville to the Keys</h1>
<p class="wp-dek">
40 mandated hospitals · 11 CBSAs · before PY2 (2027)
</p>
<p class="wp-meta">
Jennifer Tim-Diamond for Rainfall Health · September 2026<br>Every CMS TEAM-mandated hospital in Florida, verified against the live CMS roster and readmissions data — including where a previously circulated HRRP figure understated the real gap, and where the real outlier finding sits.
</p>
</section>
</div>
<div class="wp-listen-card">
<audio id="wp-audio" src="audio/index-narration.mp3" preload="metadata">
</audio>
<div class="wp-listen-panel">
<div class="wp-listen-grid">
<div class="wp-listen-main">
<p class="wp-listen-kicker">
Rainfall white paper · Narration
</p>
<p class="wp-listen-title">
Listen while you read
</p>
<div class="wp-listen-toolbar">
<button type="button" class="wp-play" data-action="play-pause" aria-label="Play" aria-pressed="false">
<span class="wp-play-glyph" aria-hidden="true"></span>
</button>
<button type="button" class="wp-icon-btn" data-action="back-15" aria-label="Back 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M9 7v4H4l5 5V7z"></path><path d="M13 7a5 5 0 1 1 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<button type="button" class="wp-icon-btn wp-speed-btn" data-action="speed-dial" aria-label="Playback speed 1×">
<span data-role="speed-label">1×</span>
</button>
<button type="button" class="wp-icon-btn" data-action="forward-15" aria-label="Forward 15 seconds">
<svg class="wp-icon" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" aria-hidden="true">
<path d="M15 7v4h5l-5 5V7z"></path><path d="M11 7a5 5 0 1 0 0 10"></path>
</svg>
<span class="wp-icon-tag">15</span>
</button>
<p><span class="wp-time" aria-live="polite"><span data-role="time-current">00:00</span> / <span data-role="time-duration">00:00</span></span></p>
</div>
<p><input type="range" class="wp-seek" data-action="seek" min="0" max="100" value="0" step="0.1" aria-label="Seek"></p>
</div>
</div>
</div>
</div>
<div class="wp-action-bar">
<p><a class="wp-action" href="index.pdf">Download PDF</a> <a class="wp-action" href="index-narration.txt" download="index-narration.txt">Narration script</a></p>
</div>
<div class="wp-disclaimer">
<p><strong>Methodology.</strong> Hospital counts, CBSA breakdowns, figures 1–2, and the readmissions comparison recompute on render from vendored CMS data (the TEAM participant list and HRRP dataset 9n3s-kdb3, joined by CCN). Episode-dollar and Medicare-population figures are not invented here; where this repo has no verified source, the report says so rather than repeating an unsourced estimate.</p>
</div>
<section id="at-a-glance" class="level1">
<h1>01 · At a glance</h1>
<p>Live hospital counts come from the vendored CMS TEAM participant list. The HRRP row below is computed at render time from the CMS HRRP dataset (9n3s-kdb3) joined to this scope’s roster by CCN; Medicare-population and per-episode LEJR figures are not published at hospital level, so this report states that rather than estimating them.</p>
<div class="cell">
<div id="tbl-glance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-glance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 30%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Signal</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mandated hospitals</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">Most geographically dispersed major TEAM state</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBSAs</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">Largest CBSA: Jacksonville ( 13 hospitals)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medicare beneficiaries</td>
<td style="text-align: left;">Not computed in this pipeline</td>
<td style="text-align: left;">Covered-lives scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">HRRP (all conditions)</td>
<td style="text-align: left;">61.4% vs 48.1% national</td>
<td style="text-align: left;">Readmission pressure under episode accountability</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Est. annual LEJR</td>
<td style="text-align: left;">Not published at hospital level</td>
<td style="text-align: left;">Volume concentration</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="where-the-mandate-sits" class="level1">
<h1>02 · Where the mandate sits</h1>
<p>Largest market in this scope: <strong>Jacksonville</strong> (13 hospitals).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1-cbsa.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: CMS TEAM-mandated hospitals in this scope.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">32.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deltona–Daytona Beach–Ormond Beach</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crestview–Fort Walton Beach–Destin</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lakeland–Winter Haven</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Panama City–Panama City Beach</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Punta Gorda</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arcadia</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Key West–Key Largo</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lake City</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miami–Fort Lauderdale–West Palm Beach</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tampa–St.&nbsp;Petersburg–Clearwater</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig2-region.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Concentration of TEAM-mandated hospitals.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="guide-narrative-from-the-website-team-report" class="level1">
<h1>03 · Guide narrative (from the website TEAM report)</h1>
<section id="takeaways" class="level3">
<h3 class="anchored" data-anchor-id="takeaways">Takeaways</h3>
<ul>
<li>40 hospitals across 11 CBSAs — the most geographically dispersed major TEAM state roster</li>
<li>Jacksonville is the largest market: 13 hospitals</li>
<li>AdventHealth dominates the Deltona–Daytona Beach and Lakeland–Winter Haven clusters</li>
<li>Florida’s HRRP excess-readmission rate is 61.4% vs 48.1% nationally — a real, large gap, roughly in line with the “fifth-highest” ranking that circulates, though that ranking is noisier than it sounds once every TEAM state is checked</li>
<li>Florida does <strong>not</strong> have a favorable hip/knee replacement story — the state runs close to national parity on that condition. The real outlier is heart attack (AMI) readmissions, where Florida’s rate is nearly 1.7 times the national rate, the largest single-condition gap found in any state analyzed this cycle</li>
</ul>
</section>
<section id="floridas-team-mandate-scale-geography-and-demographic-stakes" class="level2">
<h2 class="anchored" data-anchor-id="floridas-team-mandate-scale-geography-and-demographic-stakes">Florida’s TEAM mandate: scale, geography, and demographic stakes</h2>
<p>With <strong>40 hospitals</strong> across <strong>11 Core-Based Statistical Areas</strong>, Florida’s CMS TEAM mandate is geographically the most dispersed of any major TEAM state. The state stretches more than 500 miles from the Florida Panhandle’s Gulf Coast to the Florida Keys; its mandated CBSAs span distinct care markets with different health system configurations, patient populations, and post-acute landscapes. This geographic diversity makes Florida an unusually instructive case study in how TEAM impacts markets ranging from dense urban academic centers (Jacksonville’s UF Health and Mayo Clinic) to resort-adjacent community hospitals (Lower Keys Medical Center) and suburban multi-hospital systems (AdventHealth’s Daytona and Lakeland clusters).</p>
<p>CMS does not publish hospital-level Medicare-population or TEAM episode-volume figures, so this report does not carry a Florida-specific beneficiary count or LEJR episode estimate the way an earlier version of this briefing did — doing so would mean presenting an invented number as Florida data.</p>
<p><strong>Fast facts</strong></p>
<ul>
<li>40 hospitals mandated across 11 CBSAs</li>
<li>Jacksonville: 13 hospitals — largest Florida TEAM market</li>
<li>Deltona–Daytona Beach–Ormond Beach: 8 hospitals (primarily AdventHealth)</li>
<li>Crestview–Fort Walton Beach–Destin: 5 hospitals (primarily HCA Florida)</li>
<li>Lakeland–Winter Haven: 5 hospitals</li>
<li>61.4% of FL hospital-condition pairs exceed HRRP ERR 1.0, vs 48.1% nationally</li>
<li>Major systems: AdventHealth, UF Health, Baptist Health, HCA Florida, Ascension</li>
</ul>
</section>
<section id="jacksonville-floridas-largest-team-market" class="level2">
<h2 class="anchored" data-anchor-id="jacksonville-floridas-largest-team-market">Jacksonville: Florida’s largest TEAM market</h2>
<p><strong>Jacksonville</strong> is Florida’s dominant TEAM market with 13 mandated hospitals. Baptist Health operates multiple campuses in the CBSA (Jacksonville, Beaches, Nassau); <strong>UF Health Jacksonville</strong> is the academic referral center for northeast Florida, anchoring the state university system’s clinical mission in the region; <strong>Mayo Clinic</strong> operates its Southeast regional campus in Jacksonville with nationally recognized orthopedic and cardiovascular programs.</p>
<p><strong>Ascension St.&nbsp;Vincent’s</strong> operates four hospitals in the Jacksonville CBSA (Riverside, Southside, Clay County, St.&nbsp;Johns County) — a network-within-a-network that gives the Catholic health system coordinating leverage across suburban markets to the south and west. The HCA Florida presence (Memorial, Orange Park) rounds out the for-profit segment.</p>
</section>
<section id="adventhealth-and-hca-system-dominance-in-florida-team-markets" class="level2">
<h2 class="anchored" data-anchor-id="adventhealth-and-hca-system-dominance-in-florida-team-markets">AdventHealth and HCA: system dominance in Florida TEAM markets</h2>
<p><strong>AdventHealth</strong> — the Seventh-day Adventist Health System — has the largest single-system footprint in Florida’s TEAM mandate, operating facilities across multiple CBSAs, most heavily in the <strong>Deltona–Daytona Beach CBSA</strong> (the largest AdventHealth cluster in scope) and the <strong>Lakeland–Winter Haven CBSA</strong>, with an additional facility in the <strong>Punta Gorda CBSA</strong> (AdventHealth Port Charlotte). This infrastructure should, in theory, position AdventHealth favorably under TEAM by enabling systemwide episode cost monitoring and standardized discharge protocols — though, as the readmissions section below shows, that theoretical advantage does not show up as a favorable readmissions gap for Florida overall.</p>
<p><strong>HCA Florida</strong> (the Florida division of HCA Healthcare) similarly spans multiple CBSAs: Crestview–Fort Walton Beach–Destin (Fort Walton-Destin Hospital, Twin Cities Hospital), Panama City (Gulf Coast Hospital), Punta Gorda (Fawcett Hospital), and Lake City (Lake City Hospital). HCA Healthcare’s national episode-management experience, including with the predecessor BPCI Advanced program, gives its Florida facilities data infrastructure that smaller independent competitors may lack.</p>
</section>
<section id="small-market-and-rural-hospitals-the-panhandle-and-south-florida" class="level2">
<h2 class="anchored" data-anchor-id="small-market-and-rural-hospitals-the-panhandle-and-south-florida">Small-market and rural hospitals: the Panhandle and South Florida</h2>
<p>Florida’s geographic diversity extends TEAM’s reach into markets that challenge the model’s standard post-acute coordination assumptions. <strong>Lower Keys Medical Center</strong> — the only hospital in the Florida Keys and Monroe County’s sole acute care facility — serves a highly seasonal population with limited local SNF options, where post-acute placement requiring institutional care often necessitates transport to mainland Florida or Miami-Dade.</p>
<p><strong>DeSoto Memorial Hospital</strong> in Arcadia and the Lake City market similarly sit in less-resourced areas where post-acute options are more limited than in Florida’s larger metros, and where TEAM’s 30-day coordination requirements test the capacity of small case management teams. CMS’s risk adjustment framework partially accounts for geographic access constraints, but the structural challenge of managing a 30-day episode across limited rural resources is genuinely different from urban market TEAM management. None of this is verified against hospital-level cost data in this report; it is offered as market context, not a finding about any specific hospital’s performance.</p>
</section>
<section id="complete-hospital-directory-by-cbsa" class="level2">
<h2 class="anchored" data-anchor-id="complete-hospital-directory-by-cbsa">Complete hospital directory by CBSA</h2>
<p>The following table lists every CMS TEAM-mandated hospital in Florida, organized by Core-Based Statistical Area, generated at render time from the same live roster used for the counts above — so it cannot drift out of sync with them or omit a participant.</p>
<div class="cell">
<div id="tbl-directory-by-cbsa" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-directory-by-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-directory-by-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 89%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">CBSA</th>
<th style="text-align: right;">Hospitals</th>
<th style="text-align: left;">Hospitals in this CBSA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Ascension St Vincent’s Clay County · Ascension St Vincent’s Riverside · Ascension St Vincent’s Southside · Ascension St Vincent’s St Johns County · Baptist Medical Center - Beaches · Baptist Medical Center - Nassau · Baptist Medical Center Jacksonville · Ed Fraser Memorial Hospital · Flagler Hospital · Hca Florida Memorial Hospital · Hca Florida Orange Park Hospital · Mayo Clinic · Uf Health Jacksonville</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deltona–Daytona Beach–Ormond Beach</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Adventhealth Daytona Beach · Adventhealth Deland · Adventhealth Fish Memorial · Adventhealth New Smyrna Beach · Adventhealth Palm Coast · Adventhealth Palm Coast Parkway · Halifax Health /Uf Health Medical Center of Delton · Halifax Health Medical Center</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crestview–Fort Walton Beach–Destin</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Hca Florida Fort Walton-Destin Hospital · Hca Florida Twin Cities Hospital · North Okaloosa Medical Center · North Walton Doctors Hospital · Sacred Heart Hospital on the Emerald Coast</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lakeland–Winter Haven</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Adventhealth Heart of Florida · Adventhealth Lake Wales · Bartow Regional Medical Center · Lakeland Regional Medical Center · Winter Haven Hospital</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Panama City–Panama City Beach</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Ascension Sacred Heart Bay · Hca Florida Gulf Coast Hospital</td>
</tr>
<tr class="even">
<td style="text-align: left;">Punta Gorda</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Adventhealth Port Charlotte · Hca Florida Fawcett Hospital</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arcadia</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Desoto Memorial Hospital</td>
</tr>
<tr class="even">
<td style="text-align: left;">Key West–Key Largo</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Lower Keys Medical Center</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lake City</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Hca Florida Lake City Hospital</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miami–Fort Lauderdale–West Palm Beach</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Keralty Hospital</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tampa–St.&nbsp;Petersburg–Clearwater</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Morton Plant Hospital</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>(Source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">Centers for Medicare &amp; Medicaid Services (2026). TEAM participant list.</a>)</p>
</section>
<section id="readmissions-and-team-financial-exposure-in-florida" class="level2">
<h2 class="anchored" data-anchor-id="readmissions-and-team-financial-exposure-in-florida">Readmissions and TEAM financial exposure in Florida</h2>
<p>Joining Florida’s live TEAM roster to the CMS HRRP dataset (9n3s-kdb3, performance period 07/01/2021–06/30/2024) by CCN, 39 of Florida’s 40 mandated hospitals appear in the HRRP file. Across those hospitals’ condition pairs, <strong>61.4%</strong> exceed the excess readmission ratio (ERR) threshold of 1.0, against <strong>48.1%</strong> nationally. That is a real, sizable gap — larger than the figure that has previously circulated for Florida, which understated the true readmissions story here.</p>
<p>The “fifth-highest nationally” framing that circulates for Florida is directionally reasonable once every TEAM-participating state is checked, but it deserves the same caveat this report applies elsewhere: a handful of states with very small TEAM rosters — Indiana (6 hospitals, 74.1%), Georgia (13 hospitals, 64.9%), Missouri (6 hospitals, 63.0%) — post higher pooled rates than Florida, but those numbers come from far fewer hospitals and are correspondingly noisier. Among states with a large, meaningful TEAM roster, Florida’s 61.4% lands just behind New Jersey’s, making Florida the second-worst readmissions profile of any large-roster TEAM state this analysis has checked.</p>
<p>Unlike New York or Massachusetts, Florida does not have a favorable hip/knee replacement story to offset the rest of its readmissions profile. Florida’s hip and knee replacement ERR sits close to national parity: 45% of Florida hip and knee pairs exceed the threshold, against 47.9% nationally — essentially even, not a favorable split. Hip/knee replacement is a general HRRP condition with a comparatively high average ERR nationally, but that is a national fact about the condition, not something specific to Florida, and it is not what drives Florida’s number.</p>
<p>The real outlier is heart attack (AMI): <strong>82.8%</strong> of Florida’s heart-attack pairs exceed the threshold, against <strong>49.7%</strong> nationally — a gap of roughly 1.7x the national rate, the largest single-condition gap this analysis has found in any state checked so far. Florida also runs meaningfully worse than the national rate on CABG (68.8% vs 49.9%), heart failure (56.8% vs 48.9%), and COPD (68.6% vs 47.2%), and is close to national parity on pneumonia (48.7% vs 46.8%).</p>
<p>Florida’s demographic profile is a plausible contributor: Florida has long been a Medicare-heavy state, with an older, higher-acuity beneficiary population than most states, and a post-acute sector that varies widely in density between urban markets (Jacksonville) and smaller resort or retirement markets (Punta Gorda, Key West) where post-acute options are more geographically constrained. CMS does not publish hospital-level Medicare-population figures, so this report does not attach a specific beneficiary count to that intuition; it is offered as context, not a verified driver of the AMI gap specifically.</p>
<p>For TEAM purposes, the practical implication is that Florida’s readmissions risk does not concentrate where TEAM’s core procedure category (hip/knee replacement) sits — it concentrates in the medical conditions HRRP already tracks, especially heart attack care. A Florida hospital assessing its own TEAM exposure should not assume its LEJR readmissions profile is representative of its overall risk under episode accountability.</p>
<p>(Source: <a href="https://data.cms.gov/provider-data/dataset/9n3s-kdb3">Centers for Medicare &amp; Medicaid Services. HRRP supplemental data, Dataset 9n3s-kdb3.</a> — vendored copy joined to the CMS TEAM participant list by CCN for this report.)</p>
</section>
<section id="what-this-analysis-does-not-estimate" class="level2">
<h2 class="anchored" data-anchor-id="what-this-analysis-does-not-estimate">What this analysis does not estimate</h2>
<p>CMS does not publish hospital-level TEAM episode volumes or target prices in a form this repo can join to the Florida roster, so this report does not model a Florida-specific episode count, target price, or gain/loss dollar figure. An earlier version of this briefing estimated a specific annual LEJR episode count across Florida’s TEAM cohort and projected a multi-million-dollar aggregate savings figure from a hypothetical shift from SNF to home health — that episode count and the dollar figures built on it were not sourced from any CMS data this repo carries, and this report does not repeat them.</p>
<p>Optum Advisory (2025) projected that 56% of TEAM-mandated hospitals nationally will lose money once downside risk begins in Performance Year 2, averaging $1.2 million per facility — a national estimate, not a Florida-specific one, and its underlying methodology isn’t public. The Healthcare Financial Management Association (2026) similarly frames 2026 as a preparation year for TEAM hospitals generally, without a Florida-specific figure. Given Florida’s readmissions profile, particularly on heart attack care, that national risk is plausibly more acute here than the average state, but this report does not attach a number to that intuition. A hospital that wants an actual dollar estimate needs its own CMS-issued target price file, obtained through the TEAM participant portal.</p>
<p>The most effective intervention documented in the research base, per Dummit et al.&nbsp;(2016) and Finkelstein et al.&nbsp;(2021), is reducing discharge to institutional post-acute care (IRFs and SNFs) in favor of home health for clinically appropriate patients. That evidence base is specific to lower extremity joint replacement, the condition where Florida is closest to national parity — it is not necessarily the right lever for Florida’s actual outlier finding on heart attack readmissions, which is a medical, not surgical, condition with a different post-discharge care pathway.</p>
<p>(Source: <a href="https://doi.org/10.1001/jama.2016.12717">Dummit et al.&nbsp;(2016), JAMA 316(12).</a>) (Source: <a href="https://doi.org/10.1001/jama.2021.5684">Finkelstein et al.&nbsp;(2021), JAMA 325(18).</a>)</p>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently asked questions</h2>
<section id="how-many-florida-hospitals-are-mandated-for-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-many-florida-hospitals-are-mandated-for-cms-team">How many Florida hospitals are mandated for CMS TEAM?</h3>
<p>40 Florida hospitals are mandated to participate in CMS TEAM across 11 CBSAs, per the March 2026 CMS participant list.</p>
</section>
<section id="which-florida-city-has-the-most-team-mandated-hospitals" class="level3">
<h3 class="anchored" data-anchor-id="which-florida-city-has-the-most-team-mandated-hospitals">Which Florida city has the most TEAM-mandated hospitals?</h3>
<p>Jacksonville leads with 13 hospitals in the Jacksonville, FL CBSA — the largest single-city TEAM market in Florida.</p>
</section>
<section id="is-the-mayo-clinic-in-jacksonville-part-of-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="is-the-mayo-clinic-in-jacksonville-part-of-cms-team">Is the Mayo Clinic in Jacksonville part of CMS TEAM?</h3>
<p>Yes. Mayo Clinic’s Jacksonville campus is on the CMS TEAM participant list in the Jacksonville, FL CBSA.</p>
</section>
<section id="are-miami-hospitals-required-to-participate-in-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="are-miami-hospitals-required-to-participate-in-cms-team">Are Miami hospitals required to participate in CMS TEAM?</h3>
<p>Most of the Miami–Fort Lauderdale–West Palm Beach metro was not selected as a TEAM CBSA. Only one hospital in that CBSA is on the Florida roster. The Miami-Dade and Broward markets are largely excluded from the TEAM mandate.</p>
</section>
<section id="what-is-floridas-hrrp-readmission-rate" class="level3">
<h3 class="anchored" data-anchor-id="what-is-floridas-hrrp-readmission-rate">What is Florida’s HRRP readmission rate?</h3>
<p>61.4% of Florida’s hospital-condition pairs exceed the HRRP excess readmission ratio (ERR) threshold of 1.0, against 48.1% nationally, in the CMS HRRP dataset joined to Florida’s live TEAM roster by CCN. That is roughly the “fifth-highest nationally” ranking that circulates for Florida, and among states with a large TEAM roster it is second only to New Jersey. It is not driven by hip/knee replacement, where Florida is close to national parity — the largest gap is on heart attack (AMI) readmissions.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Centers for Medicare &amp; Medicaid Services. (2026). TEAM participant list (March 2026 update). CMMI. https://www.cms.gov/priorities/innovation/innovation-models/team-model</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024, August). Transforming Episode Accountability Model: Final Rule. Federal Register, 89(166), 68986–69178. https://www.federalregister.gov/documents/2024/08/28/2024-17021/medicare-program-hospital-inpatient-prospective-payment-systems</li>
<li>Centers for Medicare &amp; Medicaid Services. (2024). Hospital Readmissions Reduction Program (HRRP) FY2025 supplemental data [Data set]. CMS Provider Data Catalog, Dataset 9n3s-kdb3. https://data.cms.gov/provider-data/dataset/9n3s-kdb3</li>
<li>Dummit, L. A., Kahvecioglu, D., Marrufo, G., Rajkumar, R., Marshall, J., Tan, E., Le, S. T., Terebelo, S., Hearld, L., Xian, Y., Morishima, C., Pittman, P., Barzee, B., &amp; Conway, P. H. (2016). Association between hospital participation in a Medicare bundled payment initiative and payments and quality outcomes for lower extremity joint replacement episodes. JAMA, 316(12), 1267–1278. https://doi.org/10.1001/jama.2016.12717</li>
<li>Finkelstein, A., Ji, Y., Mahoney, N., &amp; Skinner, J. (2021). Mandatory Medicare bundled payment program for lower extremity joint replacement and discharge to institutional postacute care. JAMA, 325(18), 1879–1890. https://doi.org/10.1001/jama.2021.5684</li>
<li>Zuckerman, R. B., Sheingold, S. H., Orav, E. J., Ruhter, J., &amp; Epstein, A. M. (2016). Readmissions, observation, and the Hospital Readmissions Reduction Program. New England Journal of Medicine, 374(16), 1543–1551. https://doi.org/10.1056/NEJMsa1513024</li>
<li>American College of Surgeons. (2024). Transforming Episode Accountability Model (TEAM): ACS position and analysis. https://www.facs.org/advocacy/transforming-episode-accountability-model/</li>
<li>Healthcare Financial Management Association. (2026, March). Hospitals can use 2026 to prepare for CMS TEAM bundled payment risk. HFMA. https://www.hfma.org/payment-reimbursement-and-managed-care/hospitals-can-use-2026-to-prepare-for-cms-team-bundled-payment-risk</li>
</ol>
<div class="wp-disclaimer">
<p><strong>Disclaimer.</strong> Rainfall Health is not a hospital, health system, or health care provider. This paper is prepared by health care industry professionals, not clinicians, and does not constitute clinical, legal, financial, or regulatory advice. Roster counts and readmission figures are computed from the CMS files cited above; this paper does not assess, rate, or make claims about the quality of care provided by any individual hospital or organization.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="scripts/listen-along.js" defer=""></script>
<script src="scripts/highlight-notes.js" defer=""></script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>