<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="CMS TEAM’s mandatory sibling, CJR-X, will cover nearly every U.S. hospital by 2028. Here’s what the verified CMS numbers actually show.">

<title>CJR-X: The $725 Million Bet Coming for Every Hospital Not Already Under CMS TEAM – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles/report.css">
<link rel="stylesheet" href="../styles/stratus-media.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content page-columns page-full column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CJR-X: The $725 Million Bet Coming for Every Hospital Not Already Under CMS TEAM</h1>
</div>

<div>
  <div class="description">
    CMS TEAM’s mandatory sibling, CJR-X, will cover nearly every U.S. hospital by 2028. Here’s what the verified CMS numbers actually show.
  </div>
</div>


<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<div class="blog-shell page-columns page-full">
  <div class="blog-article-grid page-columns page-full">
    <div class="blog-prose-column page-columns page-full">
      <a href="../media.html" class="article-back-link">
        <svg width="16" height="16" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
        Back to Blogs &amp; Media
      </a>

      <header class="mb-8">
        <div class="article-tags">
          <span class="article-tag-pill">CMS TEAM</span> <span class="article-tag-pill">CJR-X</span> <span class="article-tag-pill">Medicare reimbursement</span> <span class="article-tag-pill">value-based care</span> <span class="article-tag-pill">bundled payments</span>
        </div>
        <div class="article-kicker">Media</div>
        <h1 class="article-h1">CJR-X: The $725 Million Bet Coming for Every Hospital Not Already Under CMS TEAM</h1>
        

        <div class="article-byline">
          <div class="byline-authors">
            <span class="author-chip"><img src="../assets/authors/eddie-qureshi.png" alt="Christina Keny" class="author-avatar"> <span>Christina Keny</span></span>
          </div>
          <span class="byline-dot">·</span>
          <span class="byline-date">August 10, 2026</span>

          <div class="article-share-actions">
            <a href="https://www.linkedin.com/sharing/share-offsite/?url=" target="_blank" rel="noopener noreferrer" class="share-btn" aria-label="Share on LinkedIn">
              <svg width="15" height="15" viewbox="0 0 24 24" fill="currentColor"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"></path></svg>
            </a>
            <a href="https://twitter.com/intent/tweet" target="_blank" rel="noopener noreferrer" class="share-btn" aria-label="Share on X">
              <svg width="14" height="14" viewbox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
            </a>
            
          </div>
        </div>
      </header>

      <img src="../assets/media/cjr-x-mandatory-bundled-payment-2028-banner.png" alt="CJR-X: The $725 Million Bet Coming for Every Hospital Not Already Under CMS TEAM" class="article-hero-image">

      <div class="article-body page-columns page-full">
<aside class="blog-tldr not-prose">
<div class="blog-tldr__label">
TL;DR
</div>
<div class="blog-tldr__body">
<ul>
<li>CMS finalized CJR-X on July 31, 2026 in the FY2027 IPPS Final Rule</li>
<li>Mandatory nationwide LEJR bundles launch January 1, 2028</li>
<li>Hospitals already under CMS TEAM are exempt from CJR-X</li>
<li>CMS projects $725 million in Medicare savings over five years</li>
<li>CJR-X covers one procedure type but outprojects TEAM’s savings estimate</li>
</ul>
</div>
</aside>
<hr>
<section id="a-second-mandatory-bundle-built-for-the-hospitals-team-didnt-reach" class="level2">
<h2 class="anchored" data-anchor-id="a-second-mandatory-bundle-built-for-the-hospitals-team-didnt-reach">A Second Mandatory Bundle, Built for the Hospitals TEAM Didn’t Reach</h2>
<p>Eighteen months after CMS made bundled payments mandatory for <a href="../cms-team/participating-hospitals/">721 hospitals</a> under the Transforming Episode Accountability Model, it has done it again — this time for almost everyone else.</p>
<p>On July 31, 2026, the Centers for Medicare &amp; Medicaid Services released the Fiscal Year 2027 Inpatient Prospective Payment System (IPPS) Final Rule (CMS-1849-F). Buried inside a 1,500-plus page annual payment update is the Comprehensive Care for Joint Replacement Expanded Model — CJR-X — a mandatory, nationwide bundled-payment program for lower extremity joint replacement (LEJR) surgery. It takes effect January 1, 2028.</p>
<p>The headline number CMS is using to sell it: <strong>$725 million</strong> in projected net Medicare savings over the model’s first five performance years, including $128 million in year one alone.</p>
<p>That figure is worth pausing on. <strong>CMS TEAM</strong> — which covers five surgical procedure types across 721 hospitals — is projected to save Medicare <strong>roughly $500 million</strong> over its own five-year run, on close to $30 billion in episode spending. CJR-X covers exactly one procedure category. It’s projected to outsave TEAM anyway.</p>
</section>
<section id="what-we-verified" class="level2">
<h2 class="anchored" data-anchor-id="what-we-verified">What We Verified</h2>
<p>Rainfall Health’s own July 31 statement on CJR-X cited several figures from CMS. We checked each one against CMS’s official CJR-X model page, the CMS fact sheet for the FY2027 final rule, and independent trade press coverage, rather than simply repeating them.</p>
<ul>
<li><strong>$112.7 million in CJR savings — confirmed, with one precision correction.</strong> The original CJR Model, tested in 34 Metropolitan Statistical Areas from April 2016 through December 2024, produced an estimated $112.7 million in net Medicare savings while maintaining quality of care for more than 98,000 knee and hip replacement patients across 323 hospitals — all figures CMS itself publishes. What needs correcting: this is not, as some coverage implies, “savings in the model’s last two years.” CMS attributes the $112.7 million specifically to its most recent formal evaluation, covering performance years 6 and 7 (2021–2023) — the final full evaluation period before the model ended in December 2024.</li>
<li><strong>$725 million CJR-X projection — confirmed.</strong> This is CMS’s own figure, repeated consistently across the proposed and final rule.</li>
<li><strong>January 1, 2028 launch date — confirmed, and later than originally proposed.</strong> CMS’s April 2026 proposed rule targeted an October 1, 2027 start. The final rule pushed CJR-X back three months, to January 1, 2028.</li>
<li><strong>“CMMI’s first expanded model implemented by the Trump Administration” — partially confirmed.</strong> CMS itself describes CJR-X as the Innovation Center’s first mandatory <em>expansion</em> of an existing tested model. The administration attribution is Rainfall’s own framing, not language CMS uses in its official materials.</li>
<li><strong>TEAM participant count — 721, not 741.</strong> Early 2026 coverage of TEAM cites roughly 741 hospitals; CMS’s own participant list, updated July 6, 2026, puts the mandated figure at 721 following removal of 20 hospitals ahead of launch. Use 721.</li>
</ul>
</section>
<section id="cjr-vs.-team-vs.-cjr-x-side-by-side" class="level2">
<h2 class="anchored" data-anchor-id="cjr-vs.-team-vs.-cjr-x-side-by-side">CJR vs.&nbsp;TEAM vs.&nbsp;CJR-X, Side by Side</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>CJR (2016–2024)</th>
<th>CMS TEAM (2026– )</th>
<th>CJR-X (2028– )</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Status</strong></td>
<td>Ended Dec.&nbsp;31, 2024</td>
<td>Active</td>
<td>Not yet started</td>
</tr>
<tr class="even">
<td><strong>Participation</strong></td>
<td>Mandatory, select markets</td>
<td>Mandatory, select markets</td>
<td>Mandatory, nationwide</td>
</tr>
<tr class="odd">
<td><strong>Geographic scope</strong></td>
<td>34 MSAs</td>
<td>188 CBSAs</td>
<td>Nationwide, with exemptions</td>
</tr>
<tr class="even">
<td><strong>Hospitals</strong></td>
<td>323</td>
<td>721</td>
<td>Nearly all remaining IPPS hospitals</td>
</tr>
<tr class="odd">
<td><strong>Procedures</strong></td>
<td>Hip &amp; knee replacement, inpatient only</td>
<td>5 episodes: CABG, LEJR, major bowel, hip/femur fracture, spinal fusion</td>
<td>Hip, knee &amp; ankle replacement — inpatient <em>and</em> outpatient</td>
</tr>
<tr class="even">
<td><strong>Episode window</strong></td>
<td>90 days post-discharge</td>
<td>30 days post-discharge</td>
<td>90 days post-discharge</td>
</tr>
<tr class="odd">
<td><strong>Medicare savings</strong></td>
<td>$112.7M (verified, PY6–7 eval.)</td>
<td>~$500M projected, 5 yrs</td>
<td>$725M projected, 5 yrs ($128M Yr. 1)</td>
</tr>
<tr class="even">
<td><strong>Exempt</strong></td>
<td>—</td>
<td>—</td>
<td>TEAM hospitals, Maryland hospitals, non-IPPS/OPPS facilities</td>
</tr>
<tr class="odd">
<td><strong>SNF 3-day waiver</strong></td>
<td>Yes</td>
<td>—</td>
<td>Yes</td>
</tr>
</tbody>
</table>
</section>
<section id="the-detail-everyone-glosses-over-these-models-dont-stack" class="level2">
<h2 class="anchored" data-anchor-id="the-detail-everyone-glosses-over-these-models-dont-stack">The Detail Everyone Glosses Over: These Models Don’t Stack</h2>
<p>The most consequential line in the final rule isn’t the savings projection — it’s the exemption. <strong>Hospitals already participating in CMS TEAM are exempt from CJR-X.</strong> So are hospitals in Maryland (which runs its own all-payer model) and facilities not paid under both IPPS and the Outpatient Prospective Payment System.</p>
<p>That reframes what “nationwide mandatory” actually means. CJR-X isn’t layering a second bundle on top of TEAM’s 721 hospitals — it’s extending mandatory episode accountability to the roughly several thousand acute-care hospitals TEAM’s 188-CBSA footprint didn’t reach. Combined, the two programs are the closest thing Medicare has to a universal mandatory bundled-payment floor for major surgery. Almost no non-Maryland, IPPS-and-OPPS-paid acute-care hospital in the country will sit outside one program or the other once CJR-X launches.</p>
<p>For a hospital CFO, the practical question isn’t “will we face a mandatory bundle” — for most, that’s already settled. It’s <em>which one</em>, and that’s determined entirely by TEAM’s 188-CBSA map, not by choice.</p>
</section>
<section id="where-cjrs-savings-actually-came-from" class="level2">
<h2 class="anchored" data-anchor-id="where-cjrs-savings-actually-came-from">Where CJR’s Savings Actually Came From</h2>
<p>CMS’s own evaluation attributes CJR’s savings primarily to reduced post-acute care spending — specifically, a documented shift away from skilled nursing facility (SNF) stays toward home health and outpatient rehabilitation. Complication rates, mortality, and readmissions showed no adverse change. CJR-X keeps the same 3-day SNF waiver that let CJR hospitals admit eligible beneficiaries to a SNF without a prior three-day inpatient stay — a policy lever hospitals used heavily to manage post-acute costs under the original model.</p>
<p>The expansion to outpatient joint replacement is the structural change most likely to move CJR-X’s numbers. Lower extremity joint replacement has migrated meaningfully into outpatient and ambulatory settings since CJR was designed in 2016; CJR-X is the first version of this model built to capture that shift rather than exclude it.</p>
</section>
<section id="the-industry-didnt-ask-for-this" class="level2">
<h2 class="anchored" data-anchor-id="the-industry-didnt-ask-for-this">The Industry Didn’t Ask for This</h2>
<p>CMS finalized CJR-X largely unchanged from its April 2026 proposal, despite organized opposition. The American Hospital Association asked CMS to make participation voluntary, or at minimum treat the first year as data-sharing only, with no downside financial risk for two years and upside-only risk for specially designated hospitals for the model’s full duration. The Federation of American Hospitals called the accompanying 2.3% IPPS payment update insufficient against inflation and rising uncompensated care costs. America’s Essential Hospitals went further, telling CMS directly not to mandate CJR-X participation at all.</p>
<p>None of it changed the outcome. The model is mandatory, nationwide, and starts in under 18 months.</p>
</section>
<section id="what-hospital-leaders-should-do-before-january-1-2028" class="level2">
<h2 class="anchored" data-anchor-id="what-hospital-leaders-should-do-before-january-1-2028">What Hospital Leaders Should Do Before January 1, 2028</h2>
<ol type="1">
<li><strong>Confirm your TEAM status first.</strong> If your hospital sits in one of TEAM’s 188 CBSAs and is among the 721 mandated participants, you are exempt from CJR-X — don’t build compliance infrastructure for a program that won’t apply to you.</li>
<li><strong>If you’re not in TEAM, assume CJR-X applies to you by default.</strong> The exemption list is short: TEAM participants, Maryland hospitals, and facilities outside standard IPPS/OPPS payment. Everyone else is in scope.</li>
<li><strong>Model the post-acute shift now.</strong> CJR’s savings came from SNF-to-home-health substitution. That requires post-acute network relationships and referral-pattern data most hospitals don’t currently track at the episode level.</li>
<li><strong>Watch for the outpatient expansion in your own case mix.</strong> If a meaningful share of your joint replacement volume has already moved outpatient, CJR-X’s inclusion of outpatient episodes changes your exposure calculation from what CJR ever measured.</li>
</ol>
<hr>
</section>
<section id="frequently-asked-questions" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions">Frequently Asked Questions</h2>
<p><strong>What is CJR-X and when does it start?</strong> CJR-X (Comprehensive Care for Joint Replacement Expanded Model) is a mandatory, nationwide Medicare bundled-payment model for hip, knee, and ankle replacement episodes. It was finalized in the FY2027 IPPS Final Rule on July 31, 2026, and its first performance year begins January 1, 2028.</p>
<p><strong>Is CJR-X the same as CMS TEAM?</strong> No.&nbsp;They are separate models. CMS TEAM covers five surgical episode types across 721 hospitals in 188 designated markets, with a 30-day post-discharge window. CJR-X covers only lower extremity joint replacement, applies nationwide, and uses a 90-day window. Hospitals participate in one or the other, not both.</p>
<p><strong>Which hospitals are exempt from CJR-X?</strong> Hospitals already participating in CMS TEAM, hospitals located in Maryland, and hospitals not paid under both the Inpatient and Outpatient Prospective Payment Systems.</p>
<p><strong>How much did the original CJR model save Medicare?</strong> CMS’s most recent formal evaluation, covering performance years 6 and 7 (2021–2023), estimated $112.7 million in net Medicare savings while maintaining quality of care for more than 98,000 knee and hip replacement patients across 323 hospitals.</p>
<p><strong>Why is CJR-X’s savings projection higher than TEAM’s if it covers fewer procedures?</strong> CMS projects $725 million in net savings for CJR-X over five years, versus roughly $500 million for TEAM over a comparable period, even though CJR-X addresses one procedure category against TEAM’s five. The larger participant base (nationwide vs.&nbsp;188 CBSAs) and the addition of outpatient episodes are the likely drivers, though CMS has not published a full methodological breakdown of the gap.</p>
<p><strong>What procedures does CJR-X cover that the original CJR did not?</strong> Ankle replacement, added for the first time. CJR-X also extends coverage to outpatient hospital procedures; the original CJR Model covered inpatient cases only.</p>
<p><strong>How long is a CJR-X episode of care?</strong> 90 days, beginning with the inpatient admission or outpatient procedure and continuing through 90 days post-discharge — three times the length of a CMS TEAM episode.</p>
<p><strong>Did the American Hospital Association support CJR-X?</strong> No.&nbsp;The AHA formally asked CMS to make participation voluntary or phased, with a no-downside-risk data-sharing period in year one. The Federation of American Hospitals and America’s Essential Hospitals raised similar objections. CMS finalized the model largely as originally proposed.</p>
<p><strong>Will hospitals already in TEAM also have to join CJR-X?</strong> No.&nbsp;TEAM participation is an explicit exemption from CJR-X under the final rule.</p>
<p><strong>When was CJR-X finalized and what rule is it part of?</strong> July 31, 2026, as part of the FY2027 Hospital Inpatient Prospective Payment System and Long-Term Care Hospital Prospective Payment System Final Rule (CMS-1849-F).</p>
<p><strong>What is the 3-day SNF waiver under CJR-X?</strong> A policy carried over from the original CJR Model that allows eligible beneficiaries to be admitted to a skilled nursing facility without a prior three-day inpatient hospital stay — a tool CJR hospitals used to manage post-acute costs.</p>
<p><strong>How should hospital leaders prepare before January 1, 2028?</strong> Confirm whether your hospital falls under TEAM’s 188-CBSA footprint (exempt) or not (in scope by default), then begin tracking post-acute referral patterns and outpatient joint replacement volume now — the two levers CMS data shows moved the needle under the original CJR Model.</p>
<hr>
<p><em>Sources: CMS.gov CJR-X Model overview; CMS Newsroom, “CMS Announces Nationwide Expansion of Proven Joint Replacement Program”; CMS Fact Sheet, FY 2027 Hospital IPPS/LTCH PPS Final Rule (CMS-1849-F); Federal Register, 2026-15833; American Hospital Association comment letters, April–June 2026; Bass, Berry &amp; Sims LLP; HFMA; Fierce Healthcare; TechTarget RevCycle Intelligence.</em></p>
<p><em>Christina Keny, PhD, MHA, RN, CPHQ, MBBLSS, is Vice President of Clinical AI at Rainfall Health and Associate Faculty at the University of California, San Francisco.</em></p>
      </section></div>
    </div>

    <!-- Sticky Right Featured Sidebar (Screenshots 2-4) -->
    <aside class="blog-featured not-prose" aria-labelledby="blog-featured-heading">
      <h2 id="blog-featured-heading" class="blog-featured__heading anchored">Featured</h2>
      <ul class="blog-featured__list">
        
              <li>
                <a href="../articles/the-trust-gap-health-data-governance-cora-han.html" class="blog-featured__link">
                  <img src="../assets/media/the-trust-gap-cora-han-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">The Trust Gap: Cora Han on Health Data Governance, Responsible AI, and Care Transitions</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/cms-team-safety-net-hospitals-sandra-scott.html" class="blog-featured__link">
                  <img src="../assets/media/cms-team-safety-net-hospitals-sandra-scott-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">How Is the CMS TEAM Model Reshaping Leadership at Safety Net Hospitals?</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/hip-fracture-home-scott-cooper.html" class="blog-featured__link">
                  <img src="../assets/media/hip-fracture-home-scott-cooper-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Patients Do Better at Home: Dr. Scott Cooper on Hip Fractures, TEAM, and the 90-Day Episode</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/rainfall-health-adds-three-new-rain-compliant-partners.html" class="blog-featured__link">
                  <img src="../assets/media/rain-ecosystem-partners-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Rainfall Health Adds Three New Partners to its Verified Ecosystem to Help Hospitals Meet Federal CMS Mandates</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/bundled-payment-analytics-steve-schutzer.html" class="blog-featured__link">
                  <img src="../assets/media/bundled-payment-analytics-steve-schutzer-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Physician-Led Bundled Payments Work: Dr. Steve Schutzer on 20 Years of Joint Replacement Data</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/ai-leverage-mark-adams-two-bear-capital.html" class="blog-featured__link">
                  <img src="../assets/media/ai-leverage-mark-adams.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">AI Won't Replace Nurses — It Will Give Them Leverage: Mark Adams on the Future of Healthcare AI</span>
                </a>
              </li>
            
      </ul>
    </aside>
  </div>
</div>




</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>