<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Webinar guide for mandated hospitals: five surgical episodes, three risk tracks, and how to maximize Medicare reimbursement under CMS TEAM. Full definition lives on the CMS TEAM model page.">

<title>Navigating the CMS TEAM Mandate: A Hospital Leader’s Webinar Guide – Stratus</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/rainfall-logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles/report.css">
<link rel="stylesheet" href="../styles/stratus-media.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/rainfall-logo.svg" alt="" class="navbar-logo light-content">
    <img src="../assets/rainfall-logo.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Stratus</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../media.html"> 
<span class="menu-text">Media &amp; Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-state-reports" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">State Reports</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-state-reports">    
        <li>
    <a class="dropdown-item" href="../states/california/california.html">
 <span class="dropdown-text">California (White Paper)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/new-york/index.html">
 <span class="dropdown-text">New York</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/florida/index.html">
 <span class="dropdown-text">Florida</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/new-jersey/index.html">
 <span class="dropdown-text">New Jersey</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/colorado/index.html">
 <span class="dropdown-text">Colorado</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/massachusetts/index.html">
 <span class="dropdown-text">Massachusetts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../states/pennsylvania/index.html">
 <span class="dropdown-text">Pennsylvania</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-regions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Regions</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-regions">    
        <li>
    <a class="dropdown-item" href="../regions/northeast/index.html">
 <span class="dropdown-text">Northeast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/norcal-pnw-rockies/index.html">
 <span class="dropdown-text">NorCal &amp; Rockies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/south-midwest/index.html">
 <span class="dropdown-text">South &amp; Midwest</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../regions/socal-southwest-gulf/index.html">
 <span class="dropdown-text">SoCal &amp; Southwest</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-newsletter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Newsletter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-newsletter">    
        <li>
    <a class="dropdown-item" href="../newsletter/cjr-history-team-selection/index.html">
 <span class="dropdown-text">CJR History &amp; TEAM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/the-one-hospital-towns/index.html">
 <span class="dropdown-text">One-Hospital Towns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/why-la-one-team-hospital/index.html">
 <span class="dropdown-text">Why LA Has One Hospital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../newsletter/modesto-the-market-that-lost-twice/index.html">
 <span class="dropdown-text">Modesto Market Analysis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.rainfallhealth.com/schedule-a-demo/"> 
<span class="menu-text">Request a Demo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content page-columns page-full column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Navigating the CMS TEAM Mandate: A Hospital Leader’s Webinar Guide</h1>
</div>

<div>
  <div class="description">
    Webinar guide for mandated hospitals: five surgical episodes, three risk tracks, and how to maximize Medicare reimbursement under CMS TEAM. Full definition lives on the CMS TEAM model page.
  </div>
</div>


<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<div class="blog-shell page-columns page-full">
  <div class="blog-article-grid page-columns page-full">
    <div class="blog-prose-column page-columns page-full">
      <a href="../media.html" class="article-back-link">
        <svg width="16" height="16" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
        Back to Blogs &amp; Media
      </a>

      <header class="mb-8">
        <div class="article-tags">
          <span class="article-tag-pill">CMS TEAM model</span> <span class="article-tag-pill">Medicare reimbursement</span> <span class="article-tag-pill">value-based care solutions</span> <span class="article-tag-pill">value-based care implementation</span> <span class="article-tag-pill">bundled payment analytics</span> <span class="article-tag-pill">hospital compliance</span> <span class="article-tag-pill">TEAM</span> <span class="article-tag-pill">Rainfall Health Podcast</span>
        </div>
        <div class="article-kicker">Media</div>
        <h1 class="article-h1">Navigating the CMS TEAM Mandate: A Hospital Leader's Webinar Guide</h1>
        

        <div class="article-byline">
          <div class="byline-authors">
            <span class="author-chip"><img src="../assets/authors/eddie-qureshi.png" alt="Jessica Ohlssen" class="author-avatar"> <span>Jessica Ohlssen</span></span> <span class="author-chip"><img src="../assets/authors/eddie-qureshi.png" alt="Robby Wallace" class="author-avatar"> <span>Robby Wallace</span></span>
          </div>
          <span class="byline-dot">·</span>
          <span class="byline-date">June 23, 2026</span>

          <div class="article-share-actions">
            <a href="https://www.linkedin.com/sharing/share-offsite/?url=" target="_blank" rel="noopener noreferrer" class="share-btn" aria-label="Share on LinkedIn">
              <svg width="15" height="15" viewbox="0 0 24 24" fill="currentColor"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"></path></svg>
            </a>
            <a href="https://twitter.com/intent/tweet" target="_blank" rel="noopener noreferrer" class="share-btn" aria-label="Share on X">
              <svg width="14" height="14" viewbox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
            </a>
            
            <a href="../downloads/navigating-cms-team-mandate-ebook.pdf" class="btn-download-ebook" target="_blank" rel="noopener noreferrer">
              <svg width="14" height="14" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
              <span>Download eBook</span>
            </a>
            
          </div>
        </div>
      </header>

      <img src="../assets/media/webinar-team-mandate/hero-journey.png" alt="Navigating the CMS TEAM Mandate: A Hospital Leader's Webinar Guide" class="article-hero-image">

      <div class="article-body page-columns page-full">
<div class="my-4">
<iframe width="100%" height="180" frameborder="no" scrolling="no" seamless="" src="https://share.transistor.fm/e/2b8f1726">
</iframe>
</div>
<aside class="blog-tldr not-prose">
<div class="blog-tldr__label">
TL;DR
</div>
<div class="blog-tldr__body">
<ul>
<li>TEAM is mandatory nationwide</li>
<li>721 hospitals, five surgical episodes</li>
<li>Accountability lasts 30 days post-discharge</li>
<li>Up to 20% revenue at risk</li>
<li>No opt-out for mandated hospitals</li>
</ul>
</div>
</aside>
<hr>
<section id="introduction-the-biggest-shift-in-surgical-reimbursement-in-a-decade" class="level2">
<h2 class="anchored" data-anchor-id="introduction-the-biggest-shift-in-surgical-reimbursement-in-a-decade">Introduction: The Biggest Shift in Surgical Reimbursement in a Decade</h2>
<p>On January 1, 2026, the <a href="../cms-team/">CMS TEAM model</a> went live — and for <strong>721 acute-care hospitals</strong> across <strong>188 U.S. markets</strong>, it is not optional. There is no voluntary on-ramp and no opt-out provision. For those hospitals, TEAM is now the live surface of <strong>value-based care implementation</strong>: Medicare reimbursement for five high-volume surgical procedures is tied to everything that happens from the operating room through <strong>30 days post-discharge</strong>.</p>
<p>This article is based on a Rainfall Health webinar featuring three practitioners who work inside this change daily: Jessica Ohlssen (SVP, Revenue), Robby Wallace (VP, Clinical Implementation), and Dr.&nbsp;Bradley Heiges (orthopedic surgeon, Optim Health System). It is written for CEOs and CFOs at mandated hospitals who need to understand what is at stake and what to do about it.</p>
<p><blogleadquote> TEAM holds hospitals accountable for the full surgical episode — not just what happens inside the OR, but everything that follows for 30 days after discharge. </blogleadquote></p>
<hr>
</section>
<section id="what-is-the-cms-team-model-and-what-does-value-based-care-implementation-require" class="level2">
<h2 class="anchored" data-anchor-id="what-is-the-cms-team-model-and-what-does-value-based-care-implementation-require">01 · What Is the CMS TEAM Model — and What Does Value-Based Care Implementation Require?</h2>
<p>The CMS TEAM model — <strong>Transforming Episode Accountability Model</strong> — is a mandatory, episode-based bundled-payment program operated by the CMS Innovation Center. It runs from <strong>January 1, 2026 through December 31, 2030</strong>. Unlike the voluntary programs that preceded it, CMS selected participating hospitals; they do not choose to be included.</p>
<p>Reimbursement under the TEAM model is determined by performance across four accountability buckets: <strong>quality</strong>, <strong>patient satisfaction</strong>, <strong>outcomes</strong>, and <strong>cost management</strong>. The hospital is the accountable entity — meaning the incentive payments and penalties flow to the hospital, not to individual physicians.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mandated acute-care hospitals</td>
<td><strong>721</strong> (CMS participant list, updated June 2026)</td>
</tr>
<tr class="even">
<td>Core-based statistical areas covered</td>
<td><strong>188</strong></td>
</tr>
<tr class="odd">
<td>Census regions for benchmarking</td>
<td><strong>9</strong></td>
</tr>
<tr class="even">
<td>Mandatory program run</td>
<td>January 1, 2026 – December 31, 2030</td>
</tr>
<tr class="odd">
<td>Medicare revenue at risk or upside</td>
<td>Up to <strong>20%</strong></td>
</tr>
</tbody>
</table>
<p>Learn more in our <a href="../cms-team/">CMS TEAM guide</a> and <a href="../team/">TEAM product overview</a>.</p>
<p><blogexpandableimage src="/assets/media/webinar-team-mandate/cms-team-model.svg" alt="CMS TEAM Model overview — five episodes, three participation tracks, and payment mechanics from 2026–2030"></blogexpandableimage></p>
<hr>
</section>
<section id="what-are-the-five-cms-team-surgical-episodes" class="level2">
<h2 class="anchored" data-anchor-id="what-are-the-five-cms-team-surgical-episodes">02 · What Are the Five CMS TEAM Surgical Episodes?</h2>
<p>The CMS TEAM model covers five surgical procedures. Each episode begins at the anchor procedure and covers all Medicare <strong>Part A and Part B</strong> spending through <strong>30 days post-discharge</strong> — including post-acute care, readmissions, and emergency department visits. <strong>Medicare Advantage is not included.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 32%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Episode</th>
<th>Procedure</th>
<th>Key Characteristic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LEJR</strong></td>
<td>Lower Extremity Joint Replacement</td>
<td>Highest-volume bundle; total hip and total knee arthroplasty</td>
</tr>
<tr class="even">
<td><strong>SHFFT</strong></td>
<td>Surgical Hip &amp; Femur Fracture Treatment</td>
<td>Often urgent; episode can begin before day zero</td>
</tr>
<tr class="odd">
<td><strong>Spinal Fusion</strong></td>
<td>Elective and Complex Spinal Fusion</td>
<td>Wide variation in recovery paths</td>
</tr>
<tr class="even">
<td><strong>CABG</strong></td>
<td>Coronary Artery Bypass Graft</td>
<td>Cardiac surgery; measured in part on 30-day mortality</td>
</tr>
<tr class="odd">
<td><strong>Major Bowel</strong></td>
<td>Major Bowel Procedure</td>
<td>High-acuity abdominal surgery with significant post-acute needs</td>
</tr>
</tbody>
</table>
<p><strong>Episode lifecycle:</strong> Anchor procedure → Hospital care + quality capture → 30-day post-discharge window → Annual reconciliation.</p>
<hr>
</section>
<section id="what-are-the-three-cms-team-participation-tracks" class="level2">
<h2 class="anchored" data-anchor-id="what-are-the-three-cms-team-participation-tracks">03 · What Are the Three CMS TEAM Participation Tracks?</h2>
<p>Hospitals enter the CMS TEAM model through one of three tracks. Track assignment determines the upside and downside exposure for each performance year. Most mandated hospitals that are not safety-net or rural will move to full two-sided risk after Year 1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 41%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Track</th>
<th>Timing</th>
<th>Risk Profile</th>
<th>Who It Applies To</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Track 1 — Glide Path</strong></td>
<td>Year 1 only</td>
<td>Upside-only, capped at 10%. No downside.</td>
<td>All mandated hospitals in Year 1</td>
</tr>
<tr class="even">
<td><strong>Track 2 — Lower-Risk Two-Sided</strong></td>
<td>Years 2–5, capped at 10%</td>
<td>Upside and downside, lower cap.</td>
<td>Safety-net and rural hospitals</td>
</tr>
<tr class="odd">
<td><strong>Track 3 — Full Two-Sided Risk</strong></td>
<td>All five years</td>
<td>20% stop-gain and stop-loss. Qualifies as an Advanced APM under MIPS.</td>
<td>All other mandated hospitals from Year 2</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Key escalation rule:</strong> Mandated hospitals that are not safety-net or rural automatically move from Track 1 to Track 3 after Year 1. Full two-sided risk is the destination for most systems, not the exception.</p>
</blockquote>
<section id="how-is-payment-settled-under-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-is-payment-settled-under-cms-team">How Is Payment Settled Under CMS TEAM?</h3>
<p>At annual reconciliation, CMS compares actual episode spending against a target price. The target is built from the hospital’s own historical costs, blended with a regional benchmark, and discounted by a CMS adjustment for risk. That result is then multiplied by a composite quality score — incorporating readmissions, PSI-90, THA/TKA patient-reported outcomes, and CABG 30-day mortality, among other measures.</p>
<hr>
</section>
</section>
<section id="cms-team-vs.-cjr-x-how-do-the-models-compare" class="level2">
<h2 class="anchored" data-anchor-id="cms-team-vs.-cjr-x-how-do-the-models-compare">04 · CMS TEAM vs.&nbsp;CJR-X: How Do the Models Compare?</h2>
<p>CMS has operated bundled-payment programs before. Understanding how the TEAM model differs from its predecessor, Comprehensive Joint Replacement (CJR-X), is important for hospital finance and compliance teams.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 36%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>CMS TEAM</th>
<th>CJR-X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Participation</td>
<td>Mandatory — no opt-out</td>
<td>Voluntary</td>
</tr>
<tr class="even">
<td>Procedures covered</td>
<td>5 surgical episodes</td>
<td>1 (lower extremity joint replacement)</td>
</tr>
<tr class="odd">
<td>Program duration</td>
<td>5 years (2026–2030)</td>
<td>Varies by cohort</td>
</tr>
<tr class="even">
<td>Risk tracks</td>
<td>3 tracks with automatic escalation</td>
<td>Single track structure</td>
</tr>
<tr class="odd">
<td>Maximum upside/downside</td>
<td>20% (Track 3)</td>
<td>Lower thresholds</td>
</tr>
<tr class="even">
<td>Advanced APM status</td>
<td>Yes (Track 3)</td>
<td>Limited</td>
</tr>
<tr class="odd">
<td>Accountable entity</td>
<td>Hospital</td>
<td>Hospital</td>
</tr>
</tbody>
</table>
<p>For a deeper comparison, see our related post: <a href="../post/rainfall-comments-on-cjr-x-and-team/">Rainfall Comments on CJR-X and TEAM</a>.</p>
<hr>
</section>
<section id="case-study-a-tale-of-two-hip-replacements" class="level2">
<h2 class="anchored" data-anchor-id="case-study-a-tale-of-two-hip-replacements">05 · Case Study: A Tale of Two Hip Replacements</h2>
<p>Same patient. Same surgeon. Same surgery. Two very different episodes — and two very different outcomes under the CMS TEAM model.</p>
<p><strong>Meet Randy:</strong> 68 years old. Uncontrolled type 2 diabetes. Active smoker. Anemic. Living alone, with stairs. Indicated for a right total hip replacement.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 23%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Episode Element</th>
<th>Pre-TEAM (Fragmented Care)</th>
<th>Post-TEAM (Coordinated Care)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-op risk identification</td>
<td>Not systematically assessed</td>
<td>Comorbidities flagged; smoking cessation and diabetes optimization initiated</td>
</tr>
<tr class="even">
<td>Discharge planning</td>
<td>Reactive, at discharge</td>
<td>Proactive — home safety, post-acute network aligned before surgery</td>
</tr>
<tr class="odd">
<td>Post-acute coordination</td>
<td>Minimal; patient navigates alone</td>
<td>Case management active across 30-day window</td>
</tr>
<tr class="even">
<td>Readmission</td>
<td>Higher likelihood</td>
<td>Reduced through early intervention</td>
</tr>
<tr class="odd">
<td>Episode cost</td>
<td>Unmanaged; above benchmark</td>
<td>Managed toward target price</td>
</tr>
<tr class="even">
<td>Hospital outcome</td>
<td>Penalty risk</td>
<td>Incentive payment potential</td>
</tr>
</tbody>
</table>
<p><blogexpandableimage src="/assets/media/webinar-team-mandate/randy-episode-timeline.svg" alt="Randy's episode timeline — pre-TEAM vs. post-TEAM"></blogexpandableimage></p>
<p><blogexpandableimage src="/assets/media/webinar-team-mandate/randy-pre-post-team.svg" alt="Randy's hip replacement — Pre-TEAM vs. Post-TEAM outcomes compared"></blogexpandableimage></p>
<hr>
</section>
<section id="what-is-the-financial-upside-under-cms-team" class="level2">
<h2 class="anchored" data-anchor-id="what-is-the-financial-upside-under-cms-team">06 · What Is the Financial Upside Under CMS TEAM?</h2>
<p>Rainfall analyzed a California health system’s actual <strong>2024 Medicare reimbursements</strong> across two eligible facilities and modeled the impact under the CMS TEAM model at the <strong>20% Track 3 cap</strong>. The analysis identified <strong>$73.4 million</strong> in potential new Medicare reimbursement revenue across existing service lines.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Scenario</th>
<th>Annual Impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Maximum incentive payment (upside)</td>
<td><strong>+$16 million</strong> per year</td>
</tr>
<tr class="even">
<td>Maximum penalty exposure (downside)</td>
<td><strong>–$8 million</strong> per year</td>
</tr>
<tr class="odd">
<td>5-year upside potential (full Track 3)</td>
<td>Up to <strong>$73.4 million</strong></td>
</tr>
</tbody>
</table>
<p>Rainfall performs this analysis free of charge on any mandated hospital’s 2024 Medicare billing data. Much of the underlying data is publicly available. The output is an individualized upside and downside projection specific to your service lines and historical performance.</p>
<hr>
</section>
<section id="a-surgeons-perspective-on-the-cms-team-model" class="level2">
<h2 class="anchored" data-anchor-id="a-surgeons-perspective-on-the-cms-team-model">07 · A Surgeon’s Perspective on the CMS TEAM Model</h2>
<blockquote class="blog-pull-quote blockquote">
A well-done surgery is a good starting point — but it’s not a guarantee. TEAM holds us accountable for everything that follows.
</blockquote>
<p><strong>The OR door is no longer the finish line.</strong> For most surgeons, clinical accountability has historically ended at the operation or the post-op visit. The CMS TEAM model extends that accountability across the full 30-day post-discharge window — and the comorbidities that drive complications are now part of the surgeon’s performance record.</p>
<p><strong>An opportunity, not just a penalty.</strong> For a high-volume orthopedic surgeon performing 300–700 joint replacements per year, TEAM creates a mechanism to standardize excellent care across the entire community — and to be measured and rewarded for it.</p>
<p><strong>Data over reputation.</strong> Real-time episode data — not just outcome scores — shows which surgeons are actually delivering on cost and quality. That becomes the performance standard going forward.</p>
<p><strong>Not one-size-fits-all.</strong> Roughly 20% of any TEAM implementation is specific to local environment: community resources, referral patterns, and post-acute infrastructure differ significantly between a large California health system and a rural Oklahoma hospital.</p>
<p><strong>Shared accountability, finally.</strong> TEAM unites the CPT-code world that physicians live in with the DRG world that hospitals operate in. It creates a shared financial stake that previous value-based care models rarely achieved.</p>
<hr>
</section>
<section id="how-rainfall-health-helps-mandated-hospitals-win-under-cms-team" class="level2">
<h2 class="anchored" data-anchor-id="how-rainfall-health-helps-mandated-hospitals-win-under-cms-team">08 · How Rainfall Health Helps Mandated Hospitals Win Under CMS TEAM</h2>
<p>Rainfall Health is the first and only recognized standard for Medicare-mandated models like CMS TEAM. The <strong>R.A.I.N. Compliant™</strong> platform is an AI-enabled compliance, case management, and care coordination solution built specifically for hospitals mandated under TEAM and CJR-X. R.A.I.N. Compliant™ status is achievable in approximately <strong>10 weeks</strong>. The platform is SOC 2 Type 1 and HIPAA Security Risk Analysis certified.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th>Pillar</th>
<th>What It Delivers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Compliance</strong></td>
<td>Maps the exact steps required to stay compliant with each Medicare-mandated model — signal through the noise</td>
</tr>
<tr class="even">
<td><strong>Case Management</strong></td>
<td>Product-based solution that ensures no episode goes unattended across the 30-day window</td>
</tr>
<tr class="odd">
<td><strong>Care Coordination</strong></td>
<td>Brings the post-acute network onto the same platform as the hospital — where ~60% of episode cost occurs</td>
</tr>
<tr class="even">
<td><strong>AI-Enabled Care Design</strong></td>
<td>Personalizes every episode to maximize reimbursement outcomes and quality scores</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>The 60% rule:</strong> Roughly 60% of the care — and the cost — in a CMS TEAM episode happens outside a hospital’s four walls. Winning under the model requires owning the post-discharge window, not just the operating room.</p>
</blockquote>
<hr>
</section>
<section id="frequently-asked-questions-about-the-cms-team-model" class="level2">
<h2 class="anchored" data-anchor-id="frequently-asked-questions-about-the-cms-team-model">Frequently Asked Questions About the CMS TEAM Model</h2>
<section id="what-is-the-cms-team-model" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-cms-team-model">What is the CMS TEAM model?</h3>
<p>The CMS TEAM model (Transforming Episode Accountability Model) is a mandatory Medicare bundled-payment program administered by the CMS Innovation Center. It launched January 1, 2026 and runs through December 31, 2030. It holds hospitals accountable for the cost and quality of five surgical episodes, including all Medicare Part A and B spending from the anchor procedure through 30 days post-discharge.</p>
</section>
<section id="how-many-hospitals-are-mandated-under-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-many-hospitals-are-mandated-under-cms-team">How many hospitals are mandated under CMS TEAM?</h3>
<p><strong>721</strong> acute-care hospitals across 188 core-based statistical areas are mandated to participate in the CMS TEAM model. Participation is not voluntary — CMS selected the hospitals.</p>
</section>
<section id="what-surgical-procedures-are-covered-under-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="what-surgical-procedures-are-covered-under-cms-team">What surgical procedures are covered under CMS TEAM?</h3>
<p>Five procedures: lower extremity joint replacement (LEJR), surgical hip and femur fracture treatment (SHFFT), spinal fusion, coronary artery bypass graft (CABG), and major bowel procedure.</p>
</section>
<section id="what-is-the-30-day-post-discharge-episode-window" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-30-day-post-discharge-episode-window">What is the 30-day post-discharge episode window?</h3>
<p>From the date of discharge following the anchor surgical procedure, all Medicare Part A and Part B spending for 30 days is included in the episode — readmissions, emergency department visits, post-acute care, skilled nursing, and home health, among other services. Medicare Advantage spending is excluded.</p>
</section>
<section id="what-is-the-difference-between-cms-team-track-1-track-2-and-track-3" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-cms-team-track-1-track-2-and-track-3">What is the difference between CMS TEAM Track 1, Track 2, and Track 3?</h3>
<p>Track 1 is the Year 1 entry track — upside-only with no downside risk, capped at 10%. Track 2 applies to safety-net and rural hospitals in Years 2–5, with both upside and downside capped at 10%. Track 3 is full two-sided risk at 20% stop-gain and stop-loss; it applies to all non-safety-net, non-rural hospitals from Year 2 onward and qualifies as an Advanced APM under MIPS.</p>
</section>
<section id="how-much-medicare-revenue-is-at-risk-under-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-much-medicare-revenue-is-at-risk-under-cms-team">How much Medicare revenue is at risk under CMS TEAM?</h3>
<p>Up to 20% of Medicare reimbursement from the five covered surgical episodes is at stake under Track 3. Depending on a hospital’s volume and historical performance, that can represent tens of millions of dollars annually. Rainfall’s analysis of a California health system identified $73.4 million in potential upside across five years.</p>
</section>
<section id="can-a-hospital-opt-out-of-the-cms-team-model" class="level3">
<h3 class="anchored" data-anchor-id="can-a-hospital-opt-out-of-the-cms-team-model">Can a hospital opt out of the CMS TEAM model?</h3>
<p>No.&nbsp;The CMS TEAM model is mandatory for the 721 hospitals CMS selected. There is no opt-out provision and no voluntary on-ramp alternative.</p>
</section>
<section id="how-does-cms-team-differ-from-cjr-x" class="level3">
<h3 class="anchored" data-anchor-id="how-does-cms-team-differ-from-cjr-x">How does CMS TEAM differ from CJR-X?</h3>
<p>CJR-X covered only lower extremity joint replacement and was a voluntary program. CMS TEAM covers five surgical procedures, is mandatory, runs five years with automatic risk escalation, and reaches a 20% upside/downside cap under Track 3 — significantly larger stakes and broader scope than CJR-X.</p>
</section>
<section id="what-is-value-based-care-under-the-cms-team-model" class="level3">
<h3 class="anchored" data-anchor-id="what-is-value-based-care-under-the-cms-team-model">What is value-based care under the CMS TEAM model?</h3>
<p>Under CMS TEAM, value-based care means the hospital’s Medicare reimbursement is tied to the quality and cost of the entire surgical episode — not just the inpatient stay. Hospitals that reduce unnecessary post-acute spending, prevent readmissions, and hit quality benchmarks receive incentive payments. Those that underperform face financial penalties.</p>
</section>
<section id="how-does-rainfall-health-help-hospitals-comply-with-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="how-does-rainfall-health-help-hospitals-comply-with-cms-team">How does Rainfall Health help hospitals comply with CMS TEAM?</h3>
<p>Rainfall Health’s R.A.I.N. Compliant™ platform provides compliance tracking, AI-enabled case management, and post-acute care coordination for all five CMS TEAM surgical episodes. Hospitals can achieve R.A.I.N. Compliant™ status in approximately 10 weeks. Rainfall also provides a free analysis of a hospital’s 2024 Medicare billings to quantify individual upside and downside under the model.</p>
</section>
<section id="when-did-the-cms-team-model-start" class="level3">
<h3 class="anchored" data-anchor-id="when-did-the-cms-team-model-start">When did the CMS TEAM model start?</h3>
<p>January 1, 2026. The program runs through December 31, 2030 — five mandatory performance years.</p>
</section>
<section id="what-happens-to-hospitals-that-do-not-prepare-for-cms-team" class="level3">
<h3 class="anchored" data-anchor-id="what-happens-to-hospitals-that-do-not-prepare-for-cms-team">What happens to hospitals that do not prepare for CMS TEAM?</h3>
<p>Hospitals that fail to manage episode costs and quality metrics face annual penalty payments up to 20% of covered episode reimbursement. For high-volume surgical programs, that exposure can reach $8 million or more per year. Additionally, unmanaged episodes under Track 3 carry both upside forfeiture and active financial penalties.</p>
<hr>
</section>
</section>
<section id="editors-note-why-this-article-uses-721-not-741" class="level2">
<h2 class="anchored" data-anchor-id="editors-note-why-this-article-uses-721-not-741">Editor’s Note: Why This Article Uses 721, Not 741</h2>
<p>When CMS finalized the TEAM model in its August 2024 IPPS Final Rule, it originally identified <strong>741 hospitals</strong> for mandatory participation. That figure was widely reported across 2024 and 2025 — and still appears in many industry publications. As of the official CMS TEAM model page (last updated July 6, 2026), the program’s listed participant count is <strong>721</strong>. CMS also published an updated participant list in June 2026. The 20-hospital reduction most likely reflects hospitals that became ineligible between the 2024 selection and the January 2026 program launch — through closure, merger, loss of IPPS designation, or CMS’s deferment policy for newly eligible hospitals. CMS has not published a press release explaining the specific reduction. The <strong>721</strong> figure is the current, authoritative count from the primary source: <a href="https://www.cms.gov/priorities/innovation/innovation-models/team-model">cms.gov/priorities/innovation/innovation-models/team-model</a>.</p>
<hr>
</section>
<section id="get-your-free-cms-team-analysis" class="level2">
<h2 class="anchored" data-anchor-id="get-your-free-cms-team-analysis">Get Your Free CMS TEAM Analysis</h2>
<p>Rainfall Health will run a free analysis of your 2024 Medicare billings and produce an individualized view of your potential upside and downside under the CMS TEAM model. Much of this data is publicly available; Rainfall turns it into your specific projection.</p>
<ul>
<li><strong>Request a demo + free analysis:</strong> <a href="../schedule-a-demo/" target="_blank" rel="noopener noreferrer">rainfallhealth.com/schedule-a-demo</a></li>
<li><strong>Learn more about the platform:</strong> <a href="../team/" target="_blank" rel="noopener noreferrer">rainfallhealth.com/team</a></li>
<li><strong>Contact Jessica Ohlssen:</strong> <a href="mailto:johlssen@rainfallhealth.com" target="_blank" rel="noopener noreferrer">johlssen@rainfallhealth.com</a></li>
<li><strong>Download the PDF version:</strong> <a href="../downloads/navigating-cms-team-mandate-ebook.pdf" target="_blank" rel="noopener noreferrer">navigating-cms-team-mandate-ebook.pdf</a></li>
</ul>
<p><strong>Further reading on Rainfall:</strong></p>
<ul>
<li><a href="../cms-team/">CMS TEAM Guide</a> — overview and starting point</li>
<li><a href="../cms-team/what-is-team/">What Is TEAM?</a> — definition and model pillars</li>
<li><a href="../cms-team/participating-hospitals/list/">Hospital List</a> — search the 721 mandated hospitals</li>
<li><a href="../cms-team/maximize-revenue/">Maximize TEAM Revenue</a> — CFO playbook</li>
</ul>
<h3 id="watch-the-webinar" class="not-prose text-brand-blue mt-12 mb-4 text-xl font-bold md:text-2xl anchored">
Watch the webinar
</h3>
<div class="not-prose my-8 aspect-video w-full overflow-hidden rounded-[var(--radius-card)] shadow-card">
<p><iframe class="h-full w-full border-0" src="https://www.youtube.com/embed/rlo6tLFzGw0" title="Medicare TEAM Mandate 2026: What Hospitals Need to Know | Webinar Ep. 1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe></p>
</div>
<p>Follow us on <a href="https://www.linkedin.com/company/rainfall-health/" target="_blank" rel="noopener noreferrer">LinkedIn</a> for announcements about future webinars in our series.</p>
<hr>
<p><em>This article is for informational purposes only and is not legal, financial, or clinical advice. Figures are illustrative and based on publicly available data; individual results vary. Consult a qualified advisor for guidance specific to your organization. © 2026 Rainfall Health.</em></p>
<p><em>Jessica Ohlssen is Senior Vice President of Revenue at Rainfall Health. Robby Wallace is Vice President of Clinical Implementation at Rainfall Health.</em></p>
      </section></div>
    </div>

    <!-- Sticky Right Featured Sidebar (Screenshots 2-4) -->
    <aside class="blog-featured not-prose" aria-labelledby="blog-featured-heading">
      <h2 id="blog-featured-heading" class="blog-featured__heading anchored">Featured</h2>
      <ul class="blog-featured__list">
        
              <li>
                <a href="../articles/the-trust-gap-health-data-governance-cora-han.html" class="blog-featured__link">
                  <img src="../assets/media/the-trust-gap-cora-han-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">The Trust Gap: Cora Han on Health Data Governance, Responsible AI, and Care Transitions</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/cms-team-safety-net-hospitals-sandra-scott.html" class="blog-featured__link">
                  <img src="../assets/media/cms-team-safety-net-hospitals-sandra-scott-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">How Is the CMS TEAM Model Reshaping Leadership at Safety Net Hospitals?</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/hip-fracture-home-scott-cooper.html" class="blog-featured__link">
                  <img src="../assets/media/hip-fracture-home-scott-cooper-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Patients Do Better at Home: Dr. Scott Cooper on Hip Fractures, TEAM, and the 90-Day Episode</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/rainfall-health-adds-three-new-rain-compliant-partners.html" class="blog-featured__link">
                  <img src="../assets/media/rain-ecosystem-partners-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Rainfall Health Adds Three New Partners to its Verified Ecosystem to Help Hospitals Meet Federal CMS Mandates</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/bundled-payment-analytics-steve-schutzer.html" class="blog-featured__link">
                  <img src="../assets/media/bundled-payment-analytics-steve-schutzer-banner.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">Physician-Led Bundled Payments Work: Dr. Steve Schutzer on 20 Years of Joint Replacement Data</span>
                </a>
              </li>
            

              <li>
                <a href="../articles/ai-leverage-mark-adams-two-bear-capital.html" class="blog-featured__link">
                  <img src="../assets/media/ai-leverage-mark-adams.jpg" alt="" class="blog-featured__thumb" loading="lazy">
                  <span class="blog-featured__title">AI Won't Replace Nurses — It Will Give Them Leverage: Mark Adams on the Future of Healthcare AI</span>
                </a>
              </li>
            
      </ul>
    </aside>
  </div>
</div>




</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>